### DISCUSSION TITLE
Multiple global maintenance windows

### DISCUSSION THREAD

**Discussion by juanariastn** [TwiN/gatus#1012] [Q&A] [answered]
Hi!
First of all, thanks for the tool. It’s really simple and useful, and works great! 🙏 

Is there any way to define multiple global maintenance windows? For example, I would like to configure two:
- Weekdays during the night
- Weekends whole day 

I see that is possible "on a per-endpoint basis" since `endpoints.maintenance-windows` accepts an array of values:
```yaml
endpoints:
  - name: endpoint-1
    url: "https://example.org"
    maintenance-windows:
      - start: "07:30"
        duration: 40m
        timezone: "Europe/Berlin"
      - start: "14:30"
        duration: 1h
        timezone: "Europe/Berlin"
```

But I cannot make it work for global maintenance section:
```yaml
maintenance:
  - start: 23:00
    duration: 12h
    every: [Monday, Tuesday, Wednesday, Thursday, Friday]
  - start: 00:00
    duration: 24h
    every: [Saturday, Sunday]
```

This fails with:
```
gatus-1  | panic: error parsing config: yaml: unmarshal errors:
gatus-1  | 	  line 477: cannot unmarshal !!seq into maintenance.Config
gatus-1  | 
gatus-1  | goroutine 1 [running]:
gatus-1  | main.main()
gatus-1  | 	/app/main.go:31 +0x1f4
gatus-1 exited with code 2
```

Thanks!
