### DISCUSSION TITLE
Send SMS with Twilio to multiple numbers

### DISCUSSION THREAD

**Discussion by imrelaszlo** [TwiN/gatus#1093] [Q&A] [answered]
Hello!

Is it possible to send SMS alerting to multiple telephone numbers, based on endpoint or endpoint groups? I've tried in this form but no success, all SMS sent to the default to address:

```
alerting:
  twilio:
    sid: "..."
    token: "..."
    from: "SENDER-NUMBER"
    to: "DEFAULT-RECIPIENT"
    default-alert:
      description: "Health check failed"
      send-on-resolved: true
      failure-threshold: 2
      success-threshold: 2

endpoints:
  - name: "Test endpoint device 1"
    group: "Test endpoint group"
    url: "..."
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: email
  - name: "Test endpoint device 2"
    group: "Test endpoint group"
    url: "..."
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
      - "len([BODY]) == 0"
    alerts:
      - type: email
      - type: twilio
        to: 'RECIPIENT-1-NUMBER'
      - type: twilio
        to: 'RECIPIENT-2-NUMBER'
```

Thanks!

**Comment by TwiN** [comment, marked as answer]
You should be able to use `alerts[].provider-override` to specify different numbers, e.g.:
```yaml
endpoints:
  - name: "..."
    url: "..."
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
      - "len([BODY]) == 0"
    alerts:
      - type: twilio
        provider-override:
          to: "RECIPIENT-1-NUMBER"
      - type: twilio
        provider-override:
          to: "RECIPIENT-2-NUMBER"
```
