### DISCUSSION TITLE
How do I configure environment variables?

### DISCUSSION THREAD

**Discussion by kuannie1** [TwiN/gatus#556] [Q&A] [answered]
I keep struggling with environment variable configuration. I have this security section defined:
```
security:
  oidc:
    issuer-url: "https://$ISSUER_URL"
    redirect-url: "http://localhost:8080/authorization-code/callback"
    client-id: "$CLIENT_ID"
    client-secret: "$CLIENT_SECRET"
    scopes: ["openid"]
```
I've tried setting these environment variables explicitly, but I consistently get this error:
```
panic: invalid security configuration

goroutine 1 [running]:
main.main()
        /app/main.go:19 +0x1b1
```
When I copy paste these values in the config.yaml file, it works. Do Environment variables only work for PORT and DOMAIN? Or is this a feature that needs to get implemented? All of the other issues & PRs assume that Environment Variables were set already.

I've tried ${ENV} and $ENV, but that doesn't help.

I run gatus with this command:
```
$ <load env vars> docker run -p 8080:8080 --mount type=bind,source="$(pwd)"/config.yaml,target=/config/config.yaml --name gatus twinproduction/gatus
```
