### DISCUSSION TITLE
Best practice to use gatus docker in order to see other docker container which are using network_mode: host option

### DISCUSSION THREAD

**Discussion by Staubgeborener** [TwiN/gatus#644] [Q&A] [answered]
I am running gatus in a docker container, there i can successfully connect all services to the dashboard which are in the same network as gatus. For example, i am running an nginx proxy manager. Gatus is in the same network as this manager so i can display the health status of the proxy manager. This setup looks like this:

```
services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest
    restart: always
    volumes:
      - ./config:/config
    networks:
      - proxy

networks:
  proxy:
    name: proxy_proxy_network
    external: true
```
```
services:
  app:
    container_name: nginx_proxy_manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy_network

networks:
  proxy_network:
```

```
[user@system ]$ docker network ls
NETWORK ID     NAME                               DRIVER    SCOPE
82fe577afae9   bridge                             bridge    local
fe877781f2a9   host                               host      local
98eea5ec0569   proxy_proxy_network                bridge    local
```

Good. 

But i also got docker container which use the `network_mode: host` parameter (for example [homebridge](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker#step-2-create-docker-compose-manifest)) so i can't assign those container to another network. How can i use gatus in order, that gatus can see containers which are using `network_mode: host`? I also thought about setting gatus itself also in `network_mode: host`, so gatus can see everything in my network (which sounds pretty bad, but should work). Problem: Gatus **HAS** to be in the proxy docker network, because the proxy manager ensures that i can see the gatus dashboard on my website.

**Comment by k-jell** [comment, marked as answer]
Try adding this to your gatus configuration:
   ```
 extra_hosts:
      - "host.docker.internal:host-gateway"
```
and use it in your config like this:
endpoints:
```
  - name: back-end
    group: core
    url: "http://host.docker.internal:8123"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
```
