### DISCUSSION TITLE
Support different urls for custom alerting based on the endpoint

### DISCUSSION THREAD

**Discussion by andreas-habel** [TwiN/gatus#716] [Ideas]
We would like to use the custom alerting functionality to trigger some webhooks on firing and resolved alerts.
Unfortunately it is only possible to configure one custom alert and therefore only one static url.
In our case we would need a specific url per endpoint to hold the unique webhook url.

So it would be great if we could set the url on the endpoint and ingest it into the alert url, or have as many custom alert rules as endpoints...

``` yaml
alerting:
    custom:
        url: https://mywebhook.com/alert/[ENDPOINT_WEBHOOK_TOKEN]
   
endpoints:
    - name: website
      url: "https://twin.sh/health"
      interval: 30s
      conditions:
          - "[STATUS] == 200"
          - "[BODY].status == UP"
          - "[RESPONSE_TIME] < 300"
    alerts:
      - type: custom
        custom_token: <my-guid-token>
```
