### DISCUSSION TITLE
Monitoring status of the docker containers in the localmachine

### DISCUSSION THREAD

**Discussion by ipa-rar** [TwiN/gatus#740] [Q&A] [answered]
I am using gatus to monitor the docker container running in my host machine and I had a hard time making it discover my docker containers. The gatus is running in a docker as well. 

`docker-compose.yaml`
```

version: "3.9"

services:
  gatus:
    image: twinproduction/gatus:latest
    restart: always
    ports:
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config:/config
```

`config.yaml`  snippet
```

endpoints:
- name: redis
  url: "tcp://127.0.0.1:6379"
  interval: 60s
  conditions:
  - "[CONNECTED] == true"
```
`logs` from gatus instance.

`[watchdog.execute] Monitored group=; endpoint=redis; success=false; errors=0; duration=0s`

What could be going wrong with this setup.?

Also does gatus has an option to monitor docker container with the container-name as supported by uptimekuma?

**Comment by ipa-rar** [comment, marked as answer]
Fixed with 
```
version: "3.9"

services:
  gatus:
    image: twinproduction/gatus:latest
    restart: always
    ports:
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config:/config
    network_mode: host #fix
```
