### DISCUSSION TITLE
Getting client.timeout errors when using traefik reverse proxy

### DISCUSSION THREAD

**Discussion by CPBPILOT** [TwiN/gatus#746] [Q&A]
<img width="796" alt="Screenshot 2024-04-26 at 5 36 45 PM" src="https://github.com/TwiN/gatus/assets/47765857/f58895c5-932c-45f2-922c-7d2e666731b4">

So I have the setup shown above with two monitor check a website that is internal to my network it is not reachable from the internet. 
In one of the monitors I am checking the IP:port. with a status == 200 condition. This monitor succeeded and give a "UP" status.
The other monitor I am checking the dns name also checking for a status == 200 condition. This monitor falls and give a "Down" status with an error ```- Get "https://teto.domain.work/": context deadline exceeded (Client. Timeout exceeded while awaiting headers)```. I have tried upping the timeout to 5m and I still get a timeout but it is slightly different ```- Get "https://teto.domain.work/": dial tcp 10.20.30.45:443: connect: connection timed out```
I have also tried these same monitors in uptime-kuma and get the same results IP:PORT works and DNS Falses. This is leading me to believe the traefik is the culprit. I am a complete noob at gatus and traefik so please forgive me if I am missing something glaring. If anyone has any ideas I am all ears.   
here is my config for gatus
```
endpoints:
  - name: TETO Production Web Interface proxy
    group: ERP
    url: "https://teto.domain.work/"
    client:
      timeout: 60s
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: TETO Production Web Interface
    group: ERP
    url: "https://10.20.30.43:13001/"
    client:
      insecure: true
    interval: 30s
    conditions:
      - "[STATUS] == 200"
```        

Here is my config I have in traefik
```
http:
 #region routers 
  routers:
    TETO_PROD:
      entryPoints:
        - "https"
      rule: "Host(`teto.domain.work`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: TETO_PROD
#endregion
#region services
  services:
    TETO_PROD:
      loadBalancer:
        servers:
          - url: "https://10.20.30.43:13001"
        passHostHeader: true
#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
```
