### DISCUSSION TITLE
How to check status of services behind Authelia?

### DISCUSSION THREAD

**Discussion by poperigby** [TwiN/gatus#807] [Q&A] [answered]
I have most of my services behind Authelia, so obviously attempting to get the status of those is going to fail if I'm using HTTP. How can I reliably get their status? Local ports?

**Comment by poperigby** [comment, marked as answer]
Yeah I guess local ports is the way with `http://localhost:<PORT>`.

**Comment by lbalogh** [comment]
I wanted to add  the Gatus widget on Homepage (https://gethomepage.dev/latest/widgets/services/gatus/), having Gatus behing Authelia.

What I did is that I added an exception in Authelia to bypass auth when connexions come from my internal Docker network :

```
access_control:
  default_policy: deny

  rules:
    (...)

    - domain: 'gatus.mydomain.com'
      policy: bypass
      networks:
      - '10.100.0.0/16'
```
