### DISCUSSION TITLE
Help with [BODY] condition to monitor a keyword

### DISCUSSION THREAD

**Discussion by huseyinkogo** [TwiN/gatus#843] [Q&A] [answered]
Hi Guys,

I need help on monitoring a keyword on a webpage. 
Example: https://wsform.com/contact/
Keyword to monitor: "Your Inquiry"
 
*So i want to make sure the form on the website is actually loading.*

```
  - name: wsform
    <<: *externalserviceother
    url: "https://wsform.com"
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 4500"
      - "[BODY] == pat(*<body>Your Inquiry</body>*)"
```
