### DISCUSSION TITLE
Error gatus exec /gatus: argument list too long

### DISCUSSION THREAD

**Discussion by babreu-technisys** [TwiN/gatus#930] [Q&A]
Good day.

I am implementing Gatus in a company I work with and we have a large number of services, but it seems that there is a limit, because I am experiencing the following error when I try to add more endpoints in the config.xml

`exec /gatus: argument list too long`

Could someone help me?

```
metrics: true
alerting:
  slack:
    webhook-url: "xxxxx"

endpoints:
  - name: Informacion del ID Cliente
    alerts:
    - type: slack
      enabled: true
      failure-threshold: 1
      success-threshold: 2
      description: "healthcheck failed 1 times in a row"
      send-on-resolved: true
    conditions:
    - "[STATUS] == any(200, 400)"
    - "[RESPONSE_TIME] < 2000"
    group: servicios-banesco.general
    interval: 20s
    name: Informacion del ID Cliente - xxxxx
    method: GET
    url: xxxx
    headers:
      Authorization: secret
```
