### ISSUE TITLE
Support setting `body` alert at the endpoint level

### ISSUE THREAD

**Issue by pablomendezroyo** [TwiN/gatus#1021]
### Describe the feature request

Right now, seems like its only supported defining the body of the alert under `alerting` and not under the `endpoint ` level. e.g:
```yaml
alerting:
  custom:
    url: "https://hooks.slack.com/services/**********/**********/**********"
    method: "POST"
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_GROUP] - [ENDPOINT_NAME] - [ALERT_DESCRIPTION] - [RESULT_ERRORS]"
      }
endpoints:
  - name: website
    url: "https://twin.sh/health"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: custom
        failure-threshold: 10
        success-threshold: 3
        send-on-resolved: true
        description: "health check failed"
```

It would be great to support this at the `endpoint` level to allow more flexibility in custom alerting. It could be allowed to write the body in the endpoint level overwriting the body from the alerting level if defined. e.g
```yaml
alerting:
  custom:
    url: "https://hooks.slack.com/services/**********/**********/**********"
    method: "POST"
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_GROUP] - [ENDPOINT_NAME] - [ALERT_DESCRIPTION] - [RESULT_ERRORS]"
      }
endpoints:
  - name: website
    url: "https://twin.sh/health"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: custom
        failure-threshold: 10
        success-threshold: 3
        send-on-resolved: true
        description: "health check failed"
      body: |
        {
          "text": "this is a custom body"
        }
```

### Why do you personally want this feature to be implemented?

To have more flexibility in the custom alerting

### How long have you been using this project?

1 week 

### Additional information

It would be cool to extend this feature to placeholders 
```yaml
    placeholders:
      ALERT_TRIGGERED_OR_RESOLVED:
        TRIGGERED: "partial_outage"
        RESOLVED: "operational"
```

Extending this to be configurable at the endpoint level
