### ISSUE TITLE
Websocket endpoint silently kills Gatus instance

### ISSUE THREAD

**Issue by lholota** [TwiN/gatus#1030]
### Describe the bug

I am trying to add a probe for mosquitto's websocket interface using the configuration below. Without this configuration Gatus works as expected but when I add it, the whole instance stops probing all endpoints. Please note that I can connect to the WS endpoint using postman just fine.

```
 endpoints:
      - name: Websocket
        group: Mosquitto
        url: "ws://{{ $.Release.Name }}.{{ $.Release.Namespace }}.svc.cluster.local:9001/"
        interval: {{ $.Values.gatus.interval }}
        body: "status"
        conditions:
          - "[CONNECTED] == true"
```

### What do you see?

The entire instance just stops probing endpoints. The user interface keeps working but there's no new probe data. The messages below appear in the console log:

```
2025/03/12 21:16:00 [api.ErrorHandler] Request Timeout
2025/03/12 21:18:21 [api.ErrorHandler] Request Timeout
```

### What do you expect to see?

Gatus trying to connect to the websocket endpoint, validating it works and disconnecting in pre-configured intervals.

### List the steps that must be taken to reproduce this issue

1. Run a standard eclipse-mosquitto container with the configuration below:
```
    listener 9001
    protocol websockets
    allow_anonymous true
```
2. Try to add the configuration above to probe the endpoint

### Version

v5.16.0
