### ISSUE TITLE
Endpoint events missing

### ISSUE THREAD

**Issue by tigattack** [TwiN/gatus#1040]
### Describe the bug

Sometimes I see events missing from an endpoint. It doesn't appear to be consistent, and I haven't been able to figure out how to reliably reproduce it.

I think it's typically the most recent event that I notice missing, but I can't confidently say whether this is consistent.

Endpoint config:
```yml
  - ui:
      hide-url: true
      hide-hostname: true
    alerts:
      - type: discord
    name: will
    group: labbers
    url: https://<URL>/api/endpoint
    conditions:
      - '[BODY].labUp == yes'
```

### What do you see?

Note how the endpoint is currently healthy, but the last event is "Endpoint is unhealthy".

![Image](https://github.com/user-attachments/assets/d4b10376-d705-4f00-aa6f-000892831e96)

![Image](https://github.com/user-attachments/assets/abb997ee-69c6-4cf8-b0b7-63ead897ce9a)

### What do you expect to see?

All endpoint events (healthy, unhealthy) in the list.

### Version

v5.16.0
