### ISSUE TITLE
Using IPv6 literals form ICMP checks works, but it's wrongly displayed on dashboard

### ISSUE THREAD

**Issue by aalmenar** [TwiN/gatus#1042]
### Describe the bug

I have a sample config like:

```yaml
  - name: NAT64 Test
    url: "icmp://2001:db8:10:10::1"
    conditions:
      - "[CONNECTED] == true"
    client:
      network: "ip6"
    alerts:
      - type: telegram
```

### What do you see?

All icmps are sent correctly, but in the dashboard you see:

NAT64 Test | 2001:db8:10:10:

Effectively cutting :1 from the end of the ipv6 address.

if the address is like: 2001:db8:10:10::64 it shown on dashboard:

NAT64 Test | 2001:db8:10:10:

Also cutting :64

So there might be a bug in what is shown on the dashboard if an ipv6 literal is used cutting the last colon and all the digis in the right side of that colon.

### What do you expect to see?

I expect the dashboard to show the full ipv6 address

### Version

v5.17.0
