### ISSUE TITLE
Add `[RESULT_SUCCESS]` placeholder

### ISSUE THREAD

**Issue by pablomendezroyo** [TwiN/gatus#1046]
### Describe the feature request

Same way it exists the placeholder `[RESULT_ERRORS]` and this placeholder can be used to add some context in the alerting custom when a certain condition could not be evaluated (i.e "no such host"), it would be great to support a new placeholder `[RESULT_SUCCESS]` to add some context to the alerting if the condition was evaluated successfully. An example of alerting custom using this new placeholder would be:

```yaml
alerting:
  custom:
    url: http://localhost:8080
    method: POST
    body: |
      {
        "title": "[ENDPOINT_NAME]",
        "body": "[ALERT_TRIGGERED_OR_RESOLVED]: [ALERT_DESCRIPTION]",
        "group": "[ENDPOINT_GROUP]",
        "errors": "[RESULT_ERRORS]",
        "data": "[RESULT_SUCCESS]",
      }
    headers:
      Content-Type: "application/json"
    placeholders:
      ALERT_TRIGGERED_OR_RESOLVED:
        TRIGGERED: "Triggered"
        RESOLVED: "Resolved"
```

If `[RESULT_ERRORS]` placeholder is defined as follows:
> [RESULT_ERRORS] (resolved from the health evaluation of a given health check)

Then `[RESULT_SUCCESS]` placeholder could be defined:
> [RESULT_SUCCESS] (data returned from an endpoint successfully evaluated if any)

Something to discuss would be how this data should be parsed by default

### Why do you personally want this feature to be implemented?

It allows to have a more personified custom alerting

### How long have you been using this project?

1 month
