### ISSUE TITLE
[Endpoints] Headers not being properly sent in health check requests

### ISSUE THREAD

**Issue by shmuelarditi** [TwiN/gatus#1051]
### Describe the bug

Gatus is not properly sending headers in health check requests, causing authentication failures when trying to access endpoints protected by Cloudflare Access. The health check requests are being redirected to the Cloudflare Access login page instead of being properly authenticated.

The issue persists regardless of whether headers are configured via environment variables or directly in the configuration.

helm values:
```
  config:
    endpoints:
      - name: "my-service - authenticated health check"
        url: "https://my-service.domain.com/health/ready"
        interval: 30s
        group: New-Platform-Services
        conditions:
          - "[STATUS] == 200"
          - "[BODY].status == ok"
        client:
          timeout: 10s
          headers:
            CF-Access-Client-Id: "eddxxxxxxxxxxxxxxx.access"
            CF-Access-Client-Secret: "a1a65bxxxxxxxxxxxxxxxxx"

```

### What do you see?

1. Health check requests to endpoints protected by Cloudflare Access are failing.
2. The response contains HTML for the Cloudflare Access login page instead of the expected health check response (JSON).
3. The same endpoint works correctly when accessed via curl with proper headers.
4. Logs do not show the actual full request being sent, making debugging difficult.

### What do you expect to see?

1. Gatus should properly send the configured headers with each health check request.
2. The health check should receive the actual health check response from the endpoint.
3. The response should not be redirected to the Cloudflare Access login page.
4. Logs should show the headers being sent with the request.

### List the steps that must be taken to reproduce this issue

1. Deploy Gatus using Helm chart version 1.2.0 with Gatus image tag "stable"
2. Configure a Gatus endpoint with headers for authentication:
```yaml
endpoints:
  - name: "my-service - authenticated health check"
    url: "https://my-service.domain.com/health/ready"
    headers:
      CF-Access-Client-Id: "your-client-id"
      CF-Access-Client-Secret: "your-client-secret"
```
3. Start Gatus with the configuration
4. Observe that the health check fails and returns HTML instead of the health check response
5. Compare with a curl request using the same headers:
```bash
curl -H "CF-Access-Client-Id: your-client-id" \
     -H "CF-Access-Client-Secret: your-client-secret" \
     https://my-service.domain.com/health/ready
```
```

### Version

- Helm Chart: 1.2.0 | Gatus Version: stable

### Additional information

reduced all the sensitive info and the actual services urls for company safety, 
please any one knows what is wrong here? curl command works perfectly fine and giving me json.
