### ISSUE TITLE
ICMP checks fail when using IPv6 literal

### ISSUE THREAD

**Issue by jortgies** [TwiN/gatus#111]
I am using this simple `config.yaml`:
```
storage:
  file: /data/persistence
services:
  - name: crimson v4
    url: "icmp://31.24.148.107"
    conditions:
      - "[CONNECTED] == true"
  - name: crimson v6
    url: "icmp://[2a06:e881:5806:42:4c0:deff:fe2e:5910]"
    conditions:
      - "[CONNECTED] == true"
  - name: crimson.ortg.de
    url: "icmp://crimson.ortg.de"
    conditions:
      - "[CONNECTED] == true"
  - name: crimson tcp v6
    url: "tcp://[2a06:e881:5806:42:4c0:deff:fe2e:5910]:443"
    conditions:
      - "[CONNECTED] == true"
```

Only the ICMP-Check using the v6 literal is failing, everything else is working fine. Even the TCP-Check using the v6 literal.
I've seen that in `client/client.go` ([here](https://github.com/TwinProduction/gatus/blob/master/client/client.go#L87)) you set the `Network` to `ip4`, maybe this could cause my check to fail?

**Comment by TwinProduction** [comment]
When you say `Even the TCP-Check using the v6 literal.`, do you mean that `crimson tcp v6` works?

When I try it from my end, neither of them work. Might be a firewall or something, but when I try `icmp://[::1]`, it works regardless of whether I use `pinger.SetNetwork("ip4")`, `pinger.SetNetwork("ip6")` or `pinger.SetNetwork("ip")`

**Comment by jortgies** [comment]
> When you say `Even the TCP-Check using the v6 literal.`, do you mean that `crimson tcp v6` works?
> 
Yes, checking TCP for IPv6 works for me.

> When I try it from my end, neither of them work. Might be a firewall or something, but when I try `icmp://[::1]`, it works regardless of whether I use `pinger.SetNetwork("ip4")`, `pinger.SetNetwork("ip6")` or `pinger.SetNetwork("ip")`

This should not be a firewall issue, the host (or at least tcp port 443) is not firewalled. Are you using docker for testing this? If you don't explicitly enable IPv6 your container may not be able to reach the IPv6 internet.

I can reproduce the same behaviour using the Google DNS. ICMP does not work, while TCP Port 53 works fine.
```
  - name: google v6 icmp
    url: "icmp://[2001:4860:4860::8888]"
    conditions:
      - "[CONNECTED] == true"
  - name: google v6 tcp
    url: "tcp://[2001:4860:4860::8888]:53"
    conditions:
      - "[CONNECTED] == true"
```
