### ISSUE TITLE
Allow initial RESOLVED alert on startup

### ISSUE THREAD

**Issue by samyon196** [TwiN/gatus#1111]
### Describe the feature request

This feature would allow to optionally receive 'RESOLVED' alert for endpoints upon startup of gatus.
currently, if endpoint is down while gatus is starting - you will get the TRIGGERED alert.
however if it is up, you will not get a 'RESOLVED'

proposal:
```
alerts:
      - type: custom
        enabled: true
        send-on-resolved: true
        send-resolved-on-startup: true <<<<<<<<<<<<
```

### Why do you personally want this feature to be implemented?

If using a custom dashboard that displays active alerts on your system (low db, failing pods etc..) to monitor DOWN endpoints - there is the edge case where:
1. endpoint failed > TRIGGERED sent to external system
2. gatus crashed for some reason (lets say OOMKilled)
3. endpoint came back up
4. gatus came back up (no 'RESOLVED sent, because gatus does not know that the endpoint had a problem before)

the external system now has a zombie alert for a failed endpoint that will be kept there forever
