### ISSUE TITLE
How to setup multiple custom alerting

### ISSUE THREAD

**Issue by majianming21** [TwiN/gatus#1115]
I setup a custom  alerting  for group A and  another custom  alerting  for group B, then i want to set up two diff alerting as
```yaml
  
alerting:
  custom1:
    url: "https://hooks.abc.com/services/**********/**********/**********"
    method: "POST"
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_GROUP] - [ENDPOINT_NAME]"
      }
  custom2:
    url: "https://hooks.xyz.com/services/**********/**********/**********"
    method: "POST"
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_GROUP] - [ENDPOINT_NAME] - [ALERT_DESCRIPTION] - [RESULT_ERRORS]"
      }
```
But it not accept, what should i do?
