### ISSUE TITLE
Alerts over SMTP

### ISSUE THREAD

**Issue by randombugs** [TwiN/gatus#117]
I would really like to send alerts per mail. Is this a possible feature in the future?

Thank you for this nice piece of software!

**Comment by TwinProduction** [comment]
Since both requests are about sending mails, I'll assume that your former suggestion is what you're interested and rename the issue accordingly.

I've definitely been thinking about adding an alerting provider for mails, something like this:
```yaml
alerting:
  mail:
    host: "smtp.gmail.com"
    port: "587"
    from: "from@example.com"
    password: "hunter2"
    to: "to@example.com"
```
