### ISSUE TITLE
Endpoint order is not preserved

### ISSUE THREAD

**Issue by tiwood** [TwiN/gatus#141]
Thanks for building this great pice of software!

Right now, the order of the defined services is not reflected in the services view - it would be great if the original order would be preserved.

Example:

```yaml
- name: serviceA
- name: serviceZ
- name: serviceB
```

Actual order:
1. serviceA
2. serviceB
3. serviceZ
