### ISSUE TITLE
Single Sign-On

### ISSUE THREAD

**Issue by erviker** [TwiN/gatus#158]
SSO as an authentication option would be an awsome edtion!

**Comment by erviker** [comment]
config exsampel
```
sso:
     type: oauth2
     provider: google
     id:
     secret:
```
