### ISSUE TITLE
Feature Request: choose which IP protocol is used

### ISSUE THREAD

**Issue by Carlotronics** [TwiN/gatus#185]
Following the current OVH outage, which only partially affected the services accessible in IPv6, I think it would be a nice feature to be able to distinguish on Gatus the services accessible only in v6 or in v4.

An implementation could be by setting `services[].ip_version` to `inet` or `inet6`:

```yaml
services:
  - name: website IPv4
    url: "https://twin.sh/health"
    ip_version: inet
    conditions:
      - "[STATUS] == 200"

  - name: website IPv6
    url: "https://twin.sh/health"
    ip_version: inet6
    conditions:
      - "[STATUS] == 200"
```
