### ISSUE TITLE
Telegram Notification raises an error when [ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_NAME] - [ALERT_DESCRIPTION] variables are used in description field

### ISSUE THREAD

**Issue by Cartache** [TwiN/gatus#196]
Hi,

Thank you for this wonderful app which meets all my expections.

By customizing it, I noticed what seems to be a bug.
The use of variables in the description field of the Telegram notification service raises an exception.

```
    alerts:
      - type: telegram
        enabled: true
        description: "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_NAME] - [ALERT_DESCRIPTION]"
```

**Here is the error:**
`gatus              | 2021-11-03T14:20:15.400568091Z 2021/11/03 14:20:15 [watchdog][handleAlertsToTrigger] Failed to send an alert for endpoint=Intercom 2: call to provider alert returned status code 400: {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 197"}`

When using a static text in the description field the notification works correctly.

Cheers.
