### ISSUE TITLE
Rename storage.file to storage.path

### ISSUE THREAD

**Issue by TwiN** [TwiN/gatus#197]
Since `storage.file` doesn't make sense for `postgres`, I decided that it was worth renaming it to `path`.

Until v4.0.0, both `file` and `path` will be supported.

## Before
```yaml
storage:
  type: sqlite
  file: data.db
```

## After
```yaml
storage:
  type: sqlite
  path: data.db
```
