### ISSUE TITLE
Deprecate persistence for storage of type memory

### ISSUE THREAD

**Issue by TwiN** [TwiN/gatus#198]
If users want to have local file persistence, they should use sqlite instead.

Storage of type `memory` will continue supporting persistence until v4.0.0

## Before
```yaml
storage:
  type: memory
  path: data.db
```

## After
```yaml
storage:
  type: sqlite
  path: data.db
```
