### ISSUE TITLE
Traefik Password protected site

### ISSUE THREAD

**Issue by Sim0nW0lf** [TwiN/gatus#200]
Is there a way to monitor a password protected site which has basic authentication from Traefik?
When I try, Gatus thinks it is offline.
I need my sites inaccessible to strangers but still would like to be able to monitor them.

If that is not possible I would like to make it a feature request! :)

**Comment by TwiN** [comment]
Technically, Basic authentication just requires specifying a header, which is supported by Gatus.

It should look like this:
```yaml
endpoints:
  - name: example
    url: "https://example.org/"
    headers:
      Authorization: "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=="
    conditions:
      - "[STATUS] == 200"
```
where `dXNlcm5hbWU6cGFzc3dvcmQ=` is the result of a base64 encoding of `username:password`.
