### ISSUE TITLE
Stale endpoint on dashboard after on-the-fly config change

### ISSUE THREAD

**Issue by jboesh** [TwiN/gatus#212]
Hi

Ive created a config with my own endpoints but the default endpoints from kubernetes: https://github.com/TwiN/gatus/blob/master/.examples/kubernetes/gatus.yaml
is still monitoring and shown in my dashboard, but NOT configured in the config. so they must disapear right?

```
apiVersion: v1
kind: Namespace
metadata:
  name: gatus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
  namespace: gatus
data:
  config.yaml: |
    metrics: true
    alerting:
      telegram:
        token: "mytoken:mytoken"
        id: "@myname"
        body: |
          {
            "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [SERVICE_NAME] - [ALERT_DESCRIPTION]"
          }
    endpoints:
      - name: Mywebsite
        group: public
        url: https://mywebsite.com
        interval: 5m
        alerts:
        - type: telegram
          enabled: true
          failure-threshold: 10
          success-threshold: 3
          send-on-resolved: true
          description: "healthcheck failed"
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 500"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatus
  namespace: gatus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
      name: gatus
      namespace: gatus
    spec:
      serviceAccountName: gatus
      terminationGracePeriodSeconds: 5
      containers:
        - image: twinproduction/gatus
          imagePullPolicy: IfNotPresent
          name: gatus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 100M
            requests:
              cpu: 50m
              memory: 30M
          volumeMounts:
            - mountPath: /config
              name: gatus-config
      volumes:
        - configMap:
            name: gatus
          name: gatus-config
---
apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: gatus
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gatus
```

so when I go to gatus.mydomain.com I still see these endpoints:

- cat-fact | cat-fact.herokuapp.com
- example | example.com
- github | api.github.com
- website | twin.sh

How can I remove them?

Thanks
Regards
