### ISSUE TITLE
[BUG] - Maintenance doesn't work

### ISSUE THREAD

**Issue by zeylos** [TwiN/gatus#222]
Hi there,

I'm trying to use the maintenance as stated in the doc but I can't make it work.
Here is my config : 
```
    - alerts:
        - type: teams
          failure-threshold: 1
          success-threshold: 1
      conditions:
        - '[STATUS] == 201'
      group: test
      interval: 10m
      maintenance:
        start: 12:00
        duration: 1h
      name: test-maintenance
      url: https://www.google.com
```
I'm in UTC+1 timezone so I should be in the maintenance range but I still receive the alerts as you can see below : 
![image](https://user-images.githubusercontent.com/24226163/145812338-d8d59f92-9ace-4f07-ba12-aaaa5e5270b3.png)

I also tried to start at 13:00 but it still triggers.
There is no error in the container logs, I only have the trigger and alert sending line.

I'm using gatus on kubernetes pulling `v3.4.0`.

Any idea what's going on or how I could debug that ?

Thanks !
Zeylos
