### ISSUE TITLE
RFE: Add support for severity

### ISSUE THREAD

**Issue by kmickeletto** [TwiN/gatus#227]
I see two ways this could be implemented, with Option 2 being super versatile but becomes more complex.

#### Simple Severity
Each test has an additional option that allows you to set a 1-10 severity rating.
```
# Notice the prefixed severity on each condition.  This should make existing configurations compatible.
  - name: webserver1
    group: customer_portal
    url: "http://web1/api/v3/status"
    interval: 5m
    conditions:
      - "10::[STATUS] == 200"
      - "5::[BODY].errors == false"
      - "3::[BODY].unknownErrors == false"
      - "2::[RESPONSE_TIME] < 150"
 ```
>None = Green = 0  #This would mean the test was successful
Low = Yellow = 1-4
Medium = Orange = 5-8
High = Red = 9-10

#### Advanced Severity
Each test has an additional option that allows you to set a 1-10 severity rating.
After **all** tests are completed, sum up the severity points and then evaluate on the sum for the entire set of tests.
```
# This uses a different yaml structure and would require admins to update their configuration.
- name: webserver1
  group: customer_portal
  url: http://web1/api/v3/status
  interval: 5m
  conditions:
    status:
      severity: 10
      test: '[STATUS] == 200'
    errors:
      severity: 5
      test: '[BODY].errors == false'
    unknown_errors:
      severity: 3
      test: '[BODY].unknownErrors == false'
    response_time:
      severity: 2
      test: '[RESPONSE_TIME] < 150'
```
>None = Green = 0  #This would mean the test was successful
Low = Yellow = 1-4
Medium = Orange = 5-8
High = Red = 9-10

**Comment by PythonGermany** [comment]
I've thought about the proposed solutions and have some ideas. Maybe instead of linking priority values directly to conditions we could allow configuring new endpoint states with a priority attached to each:
```yaml
# Notice the prefixed linked states on each condition.
endpoints:   
  - name: webserver1
    group: customer_portal
    url: "http://web1/api/v3/status"
    interval: 5m
    conditions:
      - "error::[STATUS] == 200" # Same as "[STATUS] == 200" -> when no explicit state is added it will default to error state
      - "error::[BODY].errors == false"
      - "degraded::[RESPONSE_TIME] < 150" # If the condition evaluates to false it will set the endpoint state to degraded if no other state has higher priority
      - "unknown::[BODY].unknownErrors == false"

states: # New global state config
  - name: success # Default success state, always implicitly available but can be overwritten
    label: "Healthy" # Maybe default to "name" value starting uppercase
    priority: MIN_PRIORITY 
    color: SOME_STRUCTURED_COLOR_CONFIG s
  - name: error # Default error state, always implicitly available but can be overwritten
    label: "Unhealthy"
    priority: MAX_PRIORITY  -1
    color: ...
 - name: maintenance # Potential default state, always available if introduced
    label: "Maintenance"
    priority: MAX_PRIORITY
  - name: unknown # Custom state example
    priority: MAX_PRIORITY # Required for custom states
    color: ... # Required for custom state
```
This way the existing configuration would not change and states could be configured dynamically. In addition this way it will be relatively easy to configure things like custom colors and labels of the states in the UI.

How is the priority on this @TwiN? Is this still a wanted feature. It could be an awesome feature and simultaneously close many GitHub issues all at once if done correctly, e.g the issues in regards to no maintenance or degraded endpoint states.
