### ISSUE TITLE
Gotify notifications support

### ISSUE THREAD

**Issue by Tenyun** [TwiN/gatus#239]
### Describe the feature request

Send notifications from gatus to gotify via api interface.
[gotify](https://github.com/gotify/server)

### Why do you personally want this feature to be implemented?

In the last days I tried unsuccessfully to send notifications from gatus to gotify via the custom module.
The problem is that gatus can only send "body" or "headers" via the custom module.
Gotify on the other hand needs "form" or "data" as input and complains about the missing message value.
Unless I missed something I guess both tools are currently incompatible by design.

### Additional information

Since both programs are written in go, I think it should be quite easy to implement native support for gotify or at least adapt the custom module accordingly.

**Comment by TwiN** [comment]
Hey @Tenyun!

How are you configuring your custom alerting provider?

I had a look at [Gotify's API](https://gotify.net/api-docs), and it should be possible to create a message. In fact, it seems like it's using JSON, but even if it doesn't, form data is actually sent using a header and the body.

Submitting this form:
```html
<form method="POST">
  <input name="username" value="johndoe">
  <input name="password" value="hunter2">
</form>
```
is actually just sending a request with the following header:
```
Content-Type: application/x-www-form-urlencoded
```
and the following body:
```
username=johndoe&password=hunter2
```

**Comment by Tenyun** [comment]
Hi @TwiN 

At the moment my custom alert provider looks like this.

```yaml
alerting:
  custom:
   url: "http://10.0.2.20:4444/message?token=<myToken>"
   method: "POST"
   body: |
     {
             "message": "Test Message",
             "priority": 2,
             "title": "Test Title"
     }

```
I get the following error message:

```
Failed to send an alert for endpoint=Gitea: call to provider alert returned status code 400: {"error":"Bad Request","errorCode":400,"errorDescription":"Field 'message' is required"}

```

I think I still don't quite understand how to put together a custom alert.

**Comment by Tenyun** [comment]
Ok I just figured it out.
I was missing the correct headers entry in the gatus config.
My config now looks like this and works so far.

```yaml
alerting:
  custom:
   url: "http://10.0.2.20:4444/message?token=<myToken>"
   method: "POST"
   headers:
     Content-Type: "application/json"
   body: |
     {
             "message": "[ALERT_DESCRIPTION]",
             "priority": 2,
             "title": "[ENDPOINT_NAME]"
     }
```

Thanks for the quick help.
