### ISSUE TITLE
fix: hide-hostname doesn't remove sanitize errors

### ISSUE THREAD

**Issue by Chandler-Lu** [TwiN/gatus#240]
### Describe the bug

Although the url has already be hidden in web ui, the error message will expose it.

### What do you see?

![Snipaste_2022-01-20_14-48-43](https://user-images.githubusercontent.com/18322610/150288301-be80a418-1ef8-44ea-a7f4-fdd4bd495cf3.png)

### What do you expect to see?

All url will be hidden.

### List the steps that must be taken to reproduce this issue

```
  - name: Example
    group: Group 1
    url: "https://example.com"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
    ui:
      hide-hostname: true
      dont-resolve-failed-conditions: true
```

### Version

docker: twinproduction/gatus
