### ISSUE TITLE
Alerts are not getting sent when `failure-threshold = 1`

### ISSUE THREAD

**Issue by zeylos** [TwiN/gatus#254]
### Describe the bug

Hi,

I just discovered that I have a check with `failure-threshold = 1` that does not alert me if it fails only 1 time.
Looking at the logs, it looks like the "errors" counter is still 0 when the first error appears, which would explain why the alert is not triggered.
`2022/02/14 00:54:32 [watchdog][execute] Monitored group=prod; endpoint=<redacted>; success=false; errors=0; duration=466ms`

### What do you see?

Service configured with alerts and `failure-threshold = 1` does not send alert at first error.

### What do you expect to see?

Alert being sent instantly at first error.

### List the steps that must be taken to reproduce this issue

Configure a service like below
```
    - name: one-fail-test
      alerts:
        - type: *some alert type*
      failure-threshold: 1
      success-threshold: 1
      url: *some url*
```
then trigger a fail.

### Version

v3.6.0

### Additional information

Gatus is installed on Kubernetes, alerts are working fine with other services, although I don't know if the alert is triggered with `n` or `n+1` errors, `n` being the threshold configured.

Also configuring threshold to 0 doesn't work because of this
https://github.com/TwiN/gatus/blob/18d28fc3627c1ef5bcb7e764b452829b742817cb/alerting/alert/alert.go#L59-L61

**Comment by TwiN** [comment]
Hello @zeylos,

I just tried the following configuration:
```yaml
alerting:
  discord:
    webhook-url: "https://discord.com/api/webhooks/.../..."

endpoints:
  - name: test
    url: "..."
    conditions:
      - "..."
    alerts:
      - type: discord
        enabled: true
        failure-threshold: 1
        success-threshold: 5
        send-on-resolved: true
```

And it works as intended.

As for the logs:
```
2022/02/14 00:54:32 [watchdog][execute] Monitored group=prod; endpoint=<redacted>; success=false; errors=0; duration=466ms
```
The `errors=0` in that message does not relate to the number of failure, it relates to whether there was an unexpected error while evaluating the health of the service.

Based on the configuration you provided above, I believe the issue is your indentation:
```yaml
    - name: one-fail-test
      alerts:
        - type: *some alert type*
      failure-threshold: 1
      success-threshold: 1
      url: *some url*
```
should be 
```yaml
    - name: one-fail-test
      url: *some url*
      alerts:
        - type: *some alert type*
          failure-threshold: 1
          success-threshold: 1
```
