### ISSUE TITLE
Default alerts not sending

### ISSUE THREAD

**Issue by 12nick12** [TwiN/gatus#263]
### Describe the bug

Alerts not sending. I've tried numerous alerts. They show as down on the web, but no alerts are ever sent. Is there anyway to see in the logs if/when it should send out an alert?

### What do you expect to see?

I expect an alert to be sent out

### List the steps that must be taken to reproduce this issue

Edited config and nothing works. 

### Version

3.6.0

### Additional information

Example alert config using custom webhook (ntfy), but this doesn't work with email or mattermost

    alerting:
      custom:
        url: "https://ntfy.domain.com/alert"
        method: "POST"
        body: "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_NAME] - [ALERT_DESCRIPTION]"
        default-alert:
          enabled: true
          description: "health check failed"
          send-on-resolved: true
          failure-threshold: 2
          success-threshold: 2

    endpoints:
      - name: Domain.com
        url: "https://domain.com
        group: Web Hosting
        interval: 1m
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 300"

**Comment by TwiN** [comment]
Hello @12nick12! 

As the example in [the documentation](https://github.com/TwiN/gatus#setting-a-default-alert) shows, you still have to specify the alert type in the endpoint.

In your case, it would look like this:
```yaml
endpoints:
  - name: Domain.com
    url: "https://domain.com
    group: Web Hosting
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
    alerts:
      - type: custom
```

Specifying a default alert doesn't mean it applies to all endpoints, it just means that the configuration for each alerts of that type will default to these values.

I hope that helps!
