### ISSUE TITLE
JSONPath in alert.description

### ISSUE THREAD

**Issue by euh2** [TwiN/gatus#280]
### Describe the feature request

I would like to use the same information from condition response in the alert description. I use Gatus to poll the Ceph API for Health Status. It would be nice to see the actual status in the alert description.

Something like:
``` yaml
        conditions:
          - "[STATUS] == 200"
          - "[BODY].health.status == HEALTH_OK"
        alerts:
          - type: custom
            description: "Status: [BODY].health.status"
```

### Why do you personally want this feature to be implemented?

Nice to have

### How long have you been using this project?

1d
