### ISSUE TITLE
Ability to customize theme/design

### ISSUE THREAD

**Issue by gouku** [TwiN/gatus#286]
### Describe the feature request

It would be great to have the ability to customize the theme/design via custom CSS

### Why do you personally want this feature to be implemented?

This can be a simple options in yaml that let users add some custom CSS then this will be injected to the footer of the HTML output.

### How long have you been using this project?

1 mo

### Additional information

N/A

**Comment by NOCanoa** [comment]
+1, just wanted to say realy like this project so far 🚀, just the css mould need some light tweaking and it would be perfect

**Comment by NOCanoa** [comment]
@sparanoid ohh nice, dont know any next/react tho lul, my gota do somting like that, but would still be cool to have a way to add some minimal css to the standart site

**Comment by TwiN** [comment]
FYI custom CSS is now on my radar. I'm not sure how I'm going to implement it yet, but a rough idea of what I have in mind right now is that I want to make it so people can choose from multiple "themes", all of which is essentially just pre-written custom CSS under the hood, and alternatively, the ability for people to just provide their own CSS to design it as they see fit.

I've been wanting to redo Gatus' entire UI for a while now, but I just haven't had the time.

Also @sparanoid that looks amazing!

**Comment by TwiN** [comment]
Implementation will be far simpler than what I initially envisioned. For now, at least. 

Here's what the configuration will look like:
```yaml
ui:
  custom-css: |
    .endpoint-group {
      background-color: blue !important;
    }
    .endpoint-group-content {
      background-color: red !important;
    }
```
Using the example above, here's what the dashboard would look like:
![image](https://github.com/user-attachments/assets/9bce5ded-7c95-4efa-89b3-81d10ae53d6a)

**Comment by mloskot** [comment]
First, thanks @gouku for suggesting this feature and thank you @TwiN very muchfor implementing this point of customisation for Gatus and displaying an example how to use it in https://github.com/TwiN/gatus/issues/286#issuecomment-2558805393 - I have to admit, the `ui.custom-css` documentation was unclear to me like it is taking CSS snippet or URL to custom CSS or file in mounted volume, etc.

However, I've played with it and here is what I've worked out, a pretty nice number of "what can I tweak" elements :)
I thought I'll share it as a potentially useful example for other users.

```yaml
ui:
  custom-css: |
    .bg-success {
      background-color: #008444 !important;
    }
    .endpoint-group {
      background-color: #007ab5 !important;
    }
    .font-bold {
      color: #ffffff !important;
      font-family: "Roboto", "Segoe UI", Calibri, Arial, sans-serif !important;
      font-weight: 700 !important;
    }
    .font-extrabold {
      color: #ffffff !important;
      font-family: "Roboto", "Segoe UI", Calibri, Arial, sans-serif !important;
      font-weight: 800 !important;
    }
    .font-light {
      color: #ffffff !important;
      font-family: "Roboto", "Segoe UI", Calibri, Arial, sans-serif !important;
    }
    .font-medium {
      color: #ffffff !important;
      font-family: "Roboto", "Segoe UI", Calibri, Arial, sans-serif !important;
      font-weight: 700 !important;
    }
    .mb-2 {
      background-color: #0065a2 !important;
      padding: 0.3rem !important;
    }
    .mt-3 {
      display: none !important;
    }
    .text-3xl {
      font-size: 2rem !important;
      font-weight: bold !important;
      line-height: 1rem !important;
    }
```

which ends up with rendering the Gatus UI this way:

![Image](https://github.com/user-attachments/assets/cf1813d8-355b-4a78-9e17-4dee86ba86e9)

_Disclaimer: I'm no web developer, I have near zero knowledge of CSS, so please take the CSS above as 'brute-force' way of styling._
