### ISSUE TITLE
Add endpoint URL in alert notifications

### ISSUE THREAD

**Issue by gouku** [TwiN/gatus#287]
### Describe the feature request

I just found not all notifications are born equal. For example Slack:

![image](https://user-images.githubusercontent.com/9361308/172430996-6913272b-8429-4148-a07e-11203796a4db.png)

Teams:

![image](https://user-images.githubusercontent.com/9361308/172431037-0d05cfe0-358d-4ba8-b82c-82353a726c70.png)

There's no `URL` section for notifications sent to Slack. 

### Why do you personally want this feature to be implemented?

When a service dead. My first step is to check the service by hand in my browser to see if it is really dead. So I think it's important to add the URL in each notifications. Or at least there should be an option to configure it.

### How long have you been using this project?

1 mo

### Additional information

N/A

**Comment by TwiN** [comment]
I mean, _technically_ you could just specify the URL in the alert description.

To be honest, I wasn't even aware that Mattermost's alerting provider had the URL in the alert 🤣

**Comment by Voolodimer** [comment]
```
  alerts:
    - type: telegram
      enabled: true
      send-on-resolved: true
      failure-threshold: 5
      description: "[ENDPOINT_URL]"
```
This config doesn't works for me

**Comment by TwiN** [comment]
@Voolodimer That's normal -- what I meant is that at the endpoint level, you know what the URL is. It's in your configuration at `endpoints[].url`, so you could very well just include it in the description too:

```yaml
endpoints:
- name: "..."
  url: "https://example.org"
  alerts:
    - type: telegram
      enabled: true
      send-on-resolved: true
      failure-threshold: 5
      description: "error at https://example.org"
```

As for `[ENDPOINT_URL]`, it only works for the custom alerting provider.

**Comment by gouku** [comment]
@TwiN Thanks for the solution. But with this workaround we have to add it to each endpoints. I have over 100 endpoints with a default alerting configuration setup.

**Comment by asymness** [comment]
@TwiN, I can take this up and add URL to all alerting providers.

**Comment by TwiN** [comment]
To be honest, I still think the description should be left without templating for 3 reasons:
- You have to add this anyways on each of your endpoints:
```yaml
  alerts:
    - type: <provider>
```
and it's not really that much more work to add an extra `description`:
```yaml
  alerts:
    - type: <provider>
      description: "error at <url>"
```
- Templating, while super useful when it comes to reducing the length of the configuration (and let's face it, the longer your configuration, the more easy it is to feel overwhelmed), makes it harder to search for real values. Yes, yes, this is a bit of a petty point, because the alert also contains the endpoint's name and group, and you could search for either of these, but being able to just copy the error and search for the string as-is in the configuration feels a little bit more intuitive to me. Not just that, but templating also encourages making things too generic, just like the example you gave that I re-used (`error at <url>`). It would be a lot more meaningful to customize your alert descriptions for each endpoint, thus maximizing the value of these alerts.
- If `[ENDPOINT_URL]` is added, everything that the `custom` provider supports should also be added (except `[ALERT_DESCRIPTION]`, I guess): `[ENDPOINT_NAME]`, `[ENDPOINT_GROUP]` and `[ALERT_TRIGGERED_OR_RESOLVED]`. The latter is what causes an issue -- `alerting.custom.placeholders.ALERT_TRIGGERED_OR_RESOLVED` would need to be duplicated under `alert` and I don't know how I feel about that.

Anyways, I'm not 100% against it, but from my perspective, the benefits of adding this feature don't necessarily outweigh the risk. Ultimately, Gatus is a tool and how users make use of it is entirely up to them, hence why I'm not against it, but I still do try and steer Gatus in a direction that favors good practices.

**Comment by gouku** [comment]
@TwiN Thank you for explaining this. Actually because we have many nodes to monitor (100+). We use the following method to keep our config file smaller:

```yaml
defaults: &default-alerts
  alerts:
    - type: email
    - type: telegram
    - type: slack

endpoints:
  - name: web
    group: xxx
    url: "https://example.com"
    # other options here...
    conditions: # ...
    <<: *default-alerts
```

It would be great if `[ENDPOINT_URL]` is usable as a variable in description in my case.
