### ISSUE TITLE
Implement parameter to hide entire URL from UI

### ISSUE THREAD

**Issue by gouku** [TwiN/gatus#288]
### Describe the bug

See attachment:

<img width="1012" alt="Screen Shot 2022-06-08 at 8 39 35 AM" src="https://user-images.githubusercontent.com/9361308/172618980-d6f55312-e831-4665-9f1b-a4ffb2148718.png">

### What do you see?

Although the hostname got redacted. But the API key in the URI are not.

### What do you expect to see?

The whole endpoint should be redacted. Or just add an option to remove the whole error output for the public?

### List the steps that must be taken to reproduce this issue

Create an endpoint with an API key:

```yaml
  - name: test
    url: https://example.com/botApixxxxxxxxxxxxxxxxxxxx/healthcheck
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - '[BODY].result.healthy == true'
```

Wait the the error in the frontend.

### Version

3.8.0
