### ISSUE TITLE
feat(alerting): Implement ntfy provider

### ISSUE THREAD

**Issue by TwiN** [TwiN/gatus#308]
### Describe the feature request

I'd like to create an alerting provider for [binwiederhier/ntfy](https://github.com/binwiederhier/ntfy).

For other examples, see https://github.com/TwiN/gatus/tree/master/alerting/provider

Documentation should also be added in https://github.com/TwiN/gatus/blob/master/README.md#alerting

Here's an example of a similar past pull request: #299 

### Why do you personally want this feature to be implemented?

[binwiederhier/ntfy](https://github.com/binwiederhier/ntfy) allows users to send push notifications to phone/desktop via a PUT/POST request, and I believe this would be an amazing feature to add to Gatus.

### How long have you been using this project?

N/A

### Additional information

There's already an example in ntfy's documentation, but it relies on using the `custom` alert provider: https://ntfy.sh/docs/examples/#gatus (thanks to @nickexyz for adding the example)

```yaml
alerting:
  custom:
    url: "https://ntfy.sh"
    method: "POST"
    body: |
      {
        "topic": "mytopic",
        "message": "[ENDPOINT_NAME] - [ALERT_DESCRIPTION]",
        "title": "Gatus",
        "tags": ["[ALERT_TRIGGERED_OR_RESOLVED]"],
        "priority": 3
      }
    placeholders:
      ALERT_TRIGGERED_OR_RESOLVED:
        TRIGGERED: "warning"
        RESOLVED: "white_check_mark"
```

Still, it should make the implementation easier.
