### ISSUE TITLE
Post Body is not sent

### ISSUE THREAD

**Issue by pccrazy** [TwiN/gatus#331]
### Describe the bug

i am trying the following request
```yaml
endpoints:
  - name: "Testing Post"
    group: "Test Post"   
    client:
      timeout: 20s
    url: "https://jsonplaceholder.typicode.com/posts"
    method: "POST"
    interval: 5m
    graphql: false
    body: |
        {
            "title":"testing gatus",
            "body":"testing gatus"
        }
    conditions:
      - "[STATUS] == 201"
      - "has([BODY].title) == true"
      - "has([BODY].body) == true"
```

### What do you see?

currently the result is false, it seems that it cannot the body was not sent. 

![Screen Shot 2022-09-16 at 3 38 57 PM](https://user-images.githubusercontent.com/5598959/190630676-d6d7bd34-2283-4141-aca0-af33f9fe86da.png)

### What do you expect to see?

i was expecting to get the same body sent in the endpoint

### List the steps that must be taken to reproduce this issue

1- just copy the yaml config above and run it.

### Version

latest docker

### Additional information

How this endpoint work is that it returns the same body sent by the user. i was getting the same behaviour on my private endpoint. Therefore, i used jsonplaceholder to reproduce the issue easily.

**Comment by TwiN** [comment]
@pccrazy It's because you didn't specify the header `Content-Type: application/json`.

 ```yaml
endpoints:
  - name: "post"
    group: "testing"   
    url: "https://jsonplaceholder.typicode.com/posts"
    method: "POST"
    interval: 5m
    body: |
        {
            "title":"testing gatus",
            "body":"testing gatus"
        }
    headers:
      Content-Type: application/json
    conditions:
      - "[STATUS] == 201"
      - "has([BODY].title) == true"
      - "has([BODY].body) == true"
```
