### ISSUE TITLE
Support UDP endpoints

### ISSUE THREAD

**Issue by belaytzev** [TwiN/gatus#333]
### Describe the feature request

DNS servers and some VPN servers like OpenVPN work on UDP protocol. Check availability for these services possibly only by checking UDP port

### Why do you personally want this feature to be implemented?

I want check availability of some my VPN servers

### How long have you been using this project?

1 year

### Additional information

Based on [TCP](https://github.com/TwiN/gatus#monitoring-a-tcp-endpoint) check it can look like this:

```
endpoints:
  - name: dns
    url: "udp://127.0.0.1:53"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
```
