### ISSUE TITLE
Unclear error message `invalid character '<' looking for beginning of value`

### ISSUE THREAD

**Issue by salim-b** [TwiN/gatus#351]
### Describe the bug

A JSON API endpoint I'm monitoring briefly fails from time to time with the error message

```
invalid character '<' looking for beginning of value
```

The failing condition is `len([BODY].25447.bill) >= 1`.

I don't really understand what the error message is supposed to mean. No JSON payload present in the `[BODY]`?

### What do you see?

An opaque error message.

### What do you expect to see?

A clear/understandable error message.

### List the steps that must be taken to reproduce this issue

Set up an endpoint with

```yaml
- name: "TEST"
  enabled: true
  url: "https://api.votelog.ch/api/v1/bill/380b49bf-8044-4f65-a2e5-ac3a00e3e083/votes?lang=de"
  interval: 60s
  conditions:
    - "[STATUS] == 200"
    - "len([BODY].25447.bill) >= 1"
```

### Version

4.3.2
