### ISSUE TITLE
Repeating notifications

### ISSUE THREAD

**Issue by gouku** [TwiN/gatus#379]
### Describe the feature request

Ability to send repeated notifications every x min/hr if the endpoint is still offline/dead.

### Why do you personally want this feature to be implemented?

We now had over 300 nodes monitoring via Gatus and we received the notifications via Slack and Telegram. One scenario is when some nodes are offline during the weekend. We always forget to fix them in the next workday.

I've tried some other services and seems like it's a common feature to alert repeatedly if something still goes wrong.

**Comment by TwiN** [comment]
Sounds like a good idea!

Something like this:
```yaml
    alerts:
      - type: slack
        enabled: true
        description: "healthcheck failed 3 times in a row"
        send-on-resolved: true
        repeating: true
```

That said, not all alerting providers should allow this.
For instance, `pagerduty` incidents need an acknowledgement on resolve, so we probably don't want to trigger multiple alerts simultaneously for pagerduty. For Slack, Discord, Teams, Telegram, etc. it shouldn't be an issue.

**Comment by diamonddelt** [comment]
Bumping this because we'd also be interested in having this feature, particularly for the MS Teams alerting hooks. We already use send-on-resolved, but if a service was down for 6+ days and the small team missed the initial message sent to a noisy MS Teams channel, it's easy to miss or forget unless it periodically reminds you it is still failing.

**Comment by mxcd** [comment]
From what I can see, #614 is implementing this functionality ready for review

**Comment by illia-weisser** [comment]
I want this!

**Comment by TwiN** [comment]
This has been implemented and should be available under the latest tag.

Could anybody give it a try on their end and let me know if it works as intended?

**Comment by xconverge** [comment]
I am not sure this is working for me, I am using:

```
alerting:
  slack:
    webhook-url: xyz
    default-alert:
      description: "Health Check"
      send-on-resolved: true
      failure-threshold: 2
      success-threshold: 2
      minimum-reminder-interval: 48h
```

and it has been more than 48h and I did not get a reminder

I will look into it a bit more but wanted to see if anyone has had success with this yet?

**Comment by day1118** [comment]
> I am not sure this is working for me

I tried a 5m reminder and it didn't work for me either.

**Comment by xconverge** [comment]
@day1118 thanks for the confirmation, I was able to fix it in https://github.com/TwiN/gatus/pull/1226 an issue merging/applying the default config

Until that is merged/released you can specify it per-endpoint and it should work:

```
endpoints:
  - name: test-alerting
    x: ...
    y: ...
    alerts:
      - type: xyz
        minimum-reminder-interval: 5m
```
