### ISSUE TITLE
bug:  Problem with setting DNS check for an endpoint

### ISSUE THREAD

**Issue by deppressedone** [TwiN/gatus#407]
### Describe the bug

I have problem with setting the DNS check for endpoints:

if i have config something like this:

```
endpoints:
  - name: mydomain check health 
    url: "https://mydomain/health"
    group: mydomains
    interval: 30s
    client:
      insecure: false    
    conditions:
      - "[STATUS] <= 299"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 24000"
      - "[CERTIFICATE_EXPIRATION] > 720h"
      - "[DNS_RCODE] == NOERRORS"      
    alerts:
      - type: slack
        failure-threshold: 2
        success-threshold: 2
        send-on-resolved: true
        enabled: true
        description: "health check failed xxx"   
```
the       - "[DNS_RCODE] == NOERRORS"  produces only errors
I've tried to put dns inside this endpoint but it was still failing.

### What do you expect to see?

I wanted to check my dns records but I don't know how to set it up properly so on every check of my endpoint url it checks dns records also.

Any help would be appreciated
BR,
  Rado

### List the steps that must be taken to reproduce this issue

1. make the config in endpoint to check dns
2. start application
3. errors are produced.

### Version

5.1.1
