### ISSUE TITLE
Support interval timing deducting execution time (or run endpoint on a timer)

### ISSUE THREAD

**Issue by michaelkrieger** [TwiN/gatus#430]
### Describe the feature request

Currently:
 * interval is defined as "Duration to wait **between** every status check."
 * client.timeout is defined as the "Duration before timing out"
 * Assume, in this case, that the concurrency lock is disabled (otherwise this is of no matter)

The feature request is to (optionally) either:
 - the interval could have the last runtime subtracted from it
 - the interval could be triggered from a timer and started on time

The condition for this to work would be that the timeout needs to be less than or equal to the interval.

### Why do you personally want this feature to be implemented?

For an example configuration (such as below), it would mean that both ICMP pings will run exactly 60 times in 60 seconds.  Right now, those pings get out of sync as the second hop will take longer (as it typically does) and the two charts will not line up in the dashboard

```
disable-monitoring-lock: true
endpoints:
 - name: First Hop
    group: upstream
    url: "icmp://1.2.3.4"
    interval: 1s
    client.timeout: 1s
    conditions:
      - "[CONNECTED] == true"
  - name: Second Hop
    group: upstream
    url: "icmp://4.3.2.1"
    interval: 1s
    client.timeout: 1s
    conditions:
      - "[CONNECTED] == true"
```

### How long have you been using this project?

5 weeks
