### ISSUE TITLE
404 on resources when using custom path

### ISSUE THREAD

**Issue by pavanfhw** [TwiN/gatus#439]
### Describe the bug

I'm running Gatus on Docker, using traefik to expose it on `myhost.com/status`. I'm using the Traefik rule to strip the prefix. The first request to `/` get 200 but the request to the css and js files are getting 404 error. I'm think this is just a config setting that tells Gatus that its base url is `/` that I need to change but I don't have experience in web application to find it.

### What do you see?

The red request should be made to `myhost.com/status/css/app.css` `myhost.com/status/js/app.js`, but they don't have the `/status` part resulting in 404
![image](https://user-images.githubusercontent.com/69058540/220188659-c8c66a24-1bd1-4932-9ba1-663e6b613baf.png)

### What do you expect to see?

Correct routing when hosting on custom path

### List the steps that must be taken to reproduce this issue

1. Run Gatus with docker compose (with Traefik configured), like:
```
gatus:
  image: twinproduction/gatus
  volumes:
    - ./config/gatus/:/config
  expose:
    - "8080"
  labels:
    - traefik.enable=true
    - traefik.http.routers.gatus.middlewares=strip-prefix@file
    - traefik.http.routers.gatus.rule=PathPrefix(`/status`)
    - traefik.http.routers.gatus.tls=true
    - traefik.http.services.gatus.loadbalancer.server.port=8080
```
2. Access `domain.com/status` 

### Version

Built an image from master branch

### Additional information

Is there a config for "baseurl" or something I can use? If not what change do I need to make in the code so I can make a custom image for this to work? A static config to add the prefix `/status` to all requests or something like it
