### ISSUE TITLE
tls: config seems to be ignored

### ISSUE THREAD

**Issue by szinn** [TwiN/gatus#458]
### Describe the bug

I have my config set to

```
web:
  port: 443
  tls:
    certificate-file: /config/certificate.crt
    private-key-file: /config/certificate.key
```

and would expect that going to https://gatus.example.com would work as expected. However, I have to go to http://gatus.example.com

### What do you see?

Log file contains

```
2023/04/25 00:47:15 [controller][Handle] Listening on 0.0.0.0:443
```

which, when looking at the code, seems to be the non-TLS log message.

Also tried commenting out the private-key-file entry in the tls: section and no error was reported.

### What do you expect to see?

I would expect tls to be supported according to the documentation.

### List the steps that must be taken to reproduce this issue

1. start the application with a valid certificate and tls: configuration
2. navigate to the appropriate address with https://
3. expect it to work

### Version

ghcr.io/twin/gatus:v5.3.2
