### ISSUE TITLE
Unable to set maintenance interval to all day 

### ISSUE THREAD

**Issue by skhokhlov** [TwiN/gatus#470]
### Describe the bug

I'd like to maintenance interval to all weekend from 00:00 and for 24h and I can't do it due to this check https://github.com/TwiN/gatus/blob/master/config/maintenance/maintenance.go#L85. As a result, I have to use hack like 23h 59m that is not really convenient.

### What do you see?

it says `invalid maintenance duration: must be bigger than 0 (e.g. 30m)`

### List the steps that must be taken to reproduce this issue

Use the following config 
```yaml
maintenance:
  start: 00:00
  duration: 24h
  every: [Saturday, Sunday]
```
