### ISSUE TITLE
DOMAIN_EXPIRATION is negative for all .de domains

### ISSUE THREAD

**Issue by razem-io** [TwiN/gatus#490]
### Describe the bug

It seems all `*.de` domains are not working as expected.

### What do you see?

Results in an error where the returned DOMAIN_EXPIRATION is negative.

### What do you expect to see?

positive DOMAIN_EXPIRATION

### List the steps that must be taken to reproduce this issue

```
  - name: "google.de"
    url: "https://google.de"
    interval: 1h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"
```
