### ISSUE TITLE
Ability to use YAML anchors, aliases and overrides across split config files

### ISSUE THREAD

**Issue by onedr0p** [TwiN/gatus#497]
### Describe the feature request

Hi 👋🏼  Not sure if this is a bug _or_ feature. But it would be nice to have YAML anchors, aliases and overrides available in the split configuration files.

For example:

## main-config.yaml

```yaml
default-endpoint: &defaults
  group: core
  interval: 5m
  client:
    insecure: true
    timeout: 30s
  conditions:
    - "[STATUS] == 200"
```

## example-endpoint.yaml

```yaml
endpoints:
  - name: anchor-example-1
    <<: *defaults
    url: "https://example.org/"
```

When I attempted doing this I got an error saying something like `unknown override/anchor 'defaults' referenced`

### Why do you personally want this feature to be implemented?

Make configuration easier to manage in a Kubernetes environment with the [k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar) sidecar.

### How long have you been using this project?

1y

**Comment by nioncode** [comment]
Would love to have this feature as well. Maybe this could also be solved without using yaml anchors (which don't work, because each file is parsed separately), but by either introducing a top-level `default-endpoint` configuration (which would be implicitly applied to all endpoints), e.g.:
```yaml
alerting:
  email:
    ...

default-endpoint:
  interval: 5m
  alerts:
    - type: email

endpoints:
  - name: up
    # note that interval and alerts are implicitly taken from `default-endpoint`
    url: "https://www.example.com/"
    conditions:
      - "[STATUS] == 200"
```

Or by adding an implicit `inherit` (which would be a bit more verbose):
 ```yaml
alerting:
  email:
    ...

default-endpoint:
  interval: 5m
  alerts:
    - type: email

endpoints:
  - name: up
    inherit: default-endpoint
    url: "https://www.example.com/"
    conditions:
      - "[STATUS] == 200"
```
The explicit `inherit` option would allow to 1) use different 'base' classes of endpoints and 2) inherit multiple parents (don't know if this makes sense though).

For me personally, the first option (i.e. simply having a top-level `default-endpoint` that is applied to all endpoints) would be good enough, e.g. to configure intervals and alerts.

**Comment by mkhelifa** [comment]
Hello @TwiN 

+ 1 for this feature. It will help reduce for the yaml files most of the time.

Furthermore I may also suggest to add the possibility to define group settings level or a more general inheritance mechanism

Thanks a lot ;)

**Comment by TwiN** [comment]
The work itself shouldn't be too difficult, it's just a matter of deepmerging the YAML files into one YAML file before calling https://github.com/TwiN/gatus/blob/0e9df7f00fc366c56a12755694b14b1ecd0ae12d/config/config.go#L225-L226

My problem is that this is going to promote making configurations that are very hard to read, and I don't know how I feel about that 🤔

**Comment by waako** [comment]
Would it make sense to only make this available if enabled, using a flag or environment variable ?
That might reduce the risk of it promoting complex configurations out of the box.
Or maybe only apply if `GATUS_CONFIG_PATH` set to directory path and not single file, as (if I understand correctly) for the deepmerge logic similar to this needed ?  https://github.com/TwiN/gatus/blob/1e82d2f07db5c76f3881b98f6f24f22d7dbe684c/config/config.go#L161-L175

We're using the `GATUS_CONFIG_PATH` to point to a config folder, in order to have grouped endpoints in separate files (one per client) as makes it clearer to manage.  
But it means having to repeat the `default-endpoint: &defaults` anchor (with specific name) in each file currently of course, rather than maybe just "inherit" `&defaults`  and override where relevant. 

I would probably create something like  `defaults.yaml` file that contained the default yaml anchors, and inherit those in other config files, so keeping some sense of sanity as to where to look for those `<<: *defaults` values

**Comment by TwiN** [comment]
This has already been implemented. Closing.

**Comment by alex2702** [comment]
Would it be possible to get a quick example of this? I can't get it to work with a structure like this:

```yaml
# 0_defaults.yaml

default: &default
  interval: 5m
  alerts:
   - type: email
```

```yaml
# app.yaml

endpoints:
  - name: App
    <<: *default
    ...
```

Log entries when starting:
```
Reading configuration from /config/0_defaults.yaml
Reading configuration from /config/app.yaml
panic: error reading configuration from directory /config: yaml: unknown anchor 'default' referenced
```
