### ISSUE TITLE
DOMAIN_EXPIRATION not works for .br domains

### ISSUE THREAD

**Issue by allanviana-logcomex** [TwiN/gatus#504]
### Describe the bug

Any domain like *.br do not show the correct expiration time. It's working in another domains, like *.com or *.io.

### What do you see?

![image](https://github.com/TwiN/gatus/assets/83247967/ee3f2044-44d6-4c4c-ae0c-ebb686928904)

### List the steps that must be taken to reproduce this issue

Just use that example configuration:
```
  - name: "google.com.br"
    url: "tcp://google.com.br"
    interval: 168h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: "gov.br"
    url: "tcp://gov.br"
    interval: 168h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: "oab.org.br"
    url: "tcp://oab.org.br"
    interval: 168h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"
```

I'm using TCP instead of HTTPS, but this happens in both. 

### Version

v3.4.0
