### ISSUE TITLE
Not able to send alert on outlook

### ISSUE THREAD

**Issue by 221bshashank** [TwiN/gatus#581]
### Describe the bug

I am trying to send alert on outlook but it is failing with this error: Failed to send an alert for endpoint=Liveness check: tls: failed to verify certificate: x509: certificate is valid for gwm.shashank.com, not skmailrelay.shashank.net
this is my configuration:
```
alerting:
  email:
    from: "skmailrelay.shashank.net"
    password: "abc"
    host: "skmailrelay.shashank.net"
    port: 25
    to: "abc@gmail.com"

endpoints:
  - name: Liveness check
    group: Gitlab
    url: "https://git.sk.abc.example.net/-/liveness"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok" 
    alerts:
      - type: email
        send-on-resolved: true
        description: "health check failed"
```
Then I tried this:

```
alerting:
  email:
    from: "gwm.shashank.com"
    password: "abc"
    host: "gwm.shashank.com"
    port: 25
    to: "abc@gmail.com"

endpoints:
  - name: Liveness check
    group: Gitlab
    url: "https://git.sk.abc.example.net/-/liveness"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok" 
    alerts:
      - type: email
        send-on-resolved: true
        description: "health check failed"
```
**Then the error is: Failed to send an alert for endpoint=Liveness check: dial tcp 209.141.168.113:25: i/o timeout**
I also tried this:
```
alerting:
  email:
    from: "skmailrelay.shashank.net"
    password: "abc"
    host: "skmailrelay.shashank.net"
    port: 25
    to: "abc@gmail.com"
    client:
      insecure: false

endpoints:
  - name: Liveness check
    group: Gitlab
    url: "https://git.sk.abc.example.net/-/liveness"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok" 
    alerts:
      - type: email
        send-on-resolved: true
        description: "health check failed"
```

**but it seems this client:insecure functionality is not applicable to email alert type.**
so I tried this :

```
alerting:
  custom:
    from: "skmailrelay.shashank.net"
    password: "abc"
    host: "skmailrelay.shashank.net"
    port: 25
    to: "abc@gmail.com"    
    client:
      insecure: false
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_GROUP] - [ENDPOINT_NAME] - [ALERT_DESCRIPTION]"
      }
endpoints:
  - name: Liveness check
    group: Gitlab
    url: "https://git.sk.abc.example.net/-/liveness"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok" 
    alerts:
      - type: custom
        send-on-resolved: true
        description: "health check failed"
```
        
**then error is : invalid configuration**

### What do you see?

I have explained all the configurations and the errors in description.
**Last two configurations are violations I know, but I need help on the first two.** 
How and where it is checking ssl/tls, I also went through the codebase but wasn't able to find it.
Pls let me know if I am missing something.

### What do you expect to see?

Alert on outlook

### List the steps that must be taken to reproduce this issue

I have mentioned in description in detail

### Version

latest

### Additional information

pls look into this, i need to get it done ASAP
