### ISSUE TITLE
Getting same alert description in alert triggered as well as alert resolved

### ISSUE THREAD

**Issue by 221bshashank** [TwiN/gatus#592]
### Describe the bug

I am using email alerting system and configured something like this:
```
alerting:
  email:
    from: "gatus-healthcheck-no-reply@abc.com"
    password: ""
    host: "example.net"
    port: 55
    to: "Shashank.Kumar@gmail.com"
    default-alert:
      description: "Health check has failed"
      send-on-resolved: true
      failure-threshold: 2
      success-threshold: 2
    client:
      insecure: true
```

### What do you see?

I am seeing same description for triggered as well as resolved email

### What do you expect to see?

I want to see dynamic descriptions

### List the steps that must be taken to reproduce this issue

configure email alerting system

### Version

latest
