### ISSUE TITLE
Send consecutive alerts if endpoint remains unavailable

### ISSUE THREAD

**Issue by mxcd** [TwiN/gatus#599]
### Describe the feature request

Currently, when a service becomes unavailable an alert is being triggered once the failure threshold is reached.  
If the endpoint remains unavailable, no further notification is being sent out. Keeping everyone informed about a service (still) being down, it would be nice to be able to configure consecutive emails for unhealthy endpoints after a customizable interval.
 

### How long have you been using this project?

1 year

**Comment by bugrakocabay** [comment]
Maybe adding a bool flag named `consecutive` under `alerts`, that will allow sending notification on every 
`failure-threshold`'s multiple.

```
alerts:
      - type: discord
        description: "healthcheck failed"
        send-on-resolved: true
        failure-threshold: 2
        consecutive: true
```

If this works, I can implement it.

**Comment by mxcd** [comment]
Hi @bugrakocabay,  
although your interpretation of `consecutive` in terms of wording is probably more precise, it is not exactly what I intended with this feature request.  
I would imagine it to be quite annoying to be notified in the interval of the failure threshold.  
**Example:**  
```
interval: 60s
failure-threshold: 3
```
This would result in a new notification every 3 minutes.  
If I would want a notification every day (as a gentle reminder to fix something that is broken) I would not be able to configure this while keeping acceptable initial triggering times.  
Any thoughts on this?

**Comment by bugrakocabay** [comment]
Hi @mxcd ,
so what you have in mind is, having the flexibility to have different time intervals for the initial alert and subsequent reminders. For instance, you want the first alert to trigger after 3 failures (in our example, that would be after 3 minutes). But for the consecutive reminders, you want it less frequent, say, once every day instead of every 3 minutes.

If so, I think having this kind of configuration would solve it;
```
alerts:
      - type: discord
        description: "healthcheck failed"
        send-on-resolved: true
        failure-threshold: 3
        reminder-interval: 1d
```
