### ISSUE TITLE
Data not showing when any particular endpoint is opened

### ISSUE THREAD

**Issue by 221bshashank** [TwiN/gatus#629]
### Describe the bug

Since I have implemented the data persisting using PostgreSQL I am seeing an inconsistent behavior whenever I open any individual endpoint, it is supposed to give me a detailed graph and overview of the service up time but it is not. It is giving for few of the endpoint but not all of them.
it is showing like this (blank):
![image](https://github.com/TwiN/gatus/assets/54362793/9f50414e-1426-4cf1-b242-67f47d6fac05)

### What do you expect to see?

![image](https://github.com/TwiN/gatus/assets/54362793/7aef9a0b-8c73-4391-aa75-0aac6ddf3e17)

### List the steps that must be taken to reproduce this issue

NA

### Version

latest

**Comment by TwiN** [comment]
I was unable to reproduce this locally using the default configuration.

I suspect some of your endpoints use special characters, which may explain why the links are broken.

**Comment by 221bshashank** [comment]
I was able to open all the endpoints previously but after implementing the storage data persisting using PostgreSQL , I am seeing for only few of the endpoints

**Comment by TwiN** [comment]
Can you share your configuration or at least some part of it so that I may be able to use to reproduce the issue?

**Comment by 221bshashank** [comment]
This is in config.yml
`storage:
  type: postgres
  path: "postgres://postgres:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/gatus?sslmode=disable"
`
This is my postgreSQL config
```
name: postgres
image: abc.aws.net/docker-proxy/library/postgres:15.2

env:
  POSTGRES_PASSWORD: <% secret|value( "health-password" ) %> 
  PGDATA: /var/lib/postgresql/data

ports:
  - protocol: TCP
    containerPort: 5432
    external: true

memory:
  request: 5Gi

cpu:
  request: 1

mounts:
  - volume: vol-pv-health-check
    containerDir: /var/lib/postgresql
```

This is sample endpoint config for which old data is not showing when clicked on endpoint

```
  - name: Ping
    group: Jenkins | Controller 03
    url: "https://$jenkins_user_id:$jenkins_API_token@jc-aws.net/metrics/currentUser/ping"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*pong*)"
    alerts:
      - type: email
      - type: teams
````
