### ISSUE TITLE
XMPP WSS Bad Status

### ISSUE THREAD

**Issue by roughnecks** [TwiN/gatus#641]
### Describe the bug

Not sure if a bug but I cannot get the wss endpoint to work with my prosody instance.

This is my configuration:

```
  - name: prosody
    group: core
    url: "wss://woodpeckersnest.space:5281/xmpp-websocket"
    body: "status"
    conditions:
      - "[CONNECTED] == true"
      - "[BODY].result >= 0"
```

### What do you see?

![image](https://github.com/TwiN/gatus/assets/1666536/79bc6088-80da-4afb-bf4d-9c58312538fb)

### List the steps that must be taken to reproduce this issue

1. Configure wss endpoint
2. Start application
3. Look at the webpage - error in the wss endpoint

### Version

I installed with GO
