### ISSUE TITLE
feat: Allow disabling email notifications for groups

### ISSUE THREAD

**Issue by ffflorian** [TwiN/gatus#645]
### Describe the feature request

As stated in the title, I'd like to be able to disable email notifications for certain groups.

### Why do you personally want this feature to be implemented?

In my deployment I have a group for staging and a group for production. If a service from the production group goes offline, I'd like to receive an email. But not for the services from the staging group.

I *thought* this would work:

```yaml
alerting:
  email:
    from: sender@example.com
    username: example-user
    password: example-pass
    host: example.com
    port: 25
    to: user@example.com
    overrides:
      - group: staging
        enabled: false
```

But unfortunately, this results in an error on startup:
`[config][validateAlertingConfig] Ignoring provider=email because configuration is invalid`.

Then I tried this:

```yaml
alerting:
  email:
    from: sender@example.com
    username: example-user
    password: example-pass
    host: example.com
    port: 25
    to: user@example.com
    overrides:
      - group: staging
        to: ""
```

But this configuration yields the same error 🫤

I'd like to propose a configuration option like in my first try:

```yaml
    overrides:
      - group: staging
        enabled: false
```

### How long have you been using this project?

1 year
