### ISSUE TITLE
Support for Mattermost to override the default channel

### ISSUE THREAD

**Issue by beheersp** [TwiN/gatus#646]
### Describe the feature request

When using a Mattermost webhook we want to override the channel the message posts in.
In our case we got many channels and want to use a single webhook to post to all the different channels.

The channel override is supported in Mattermost as the extra channel parameter which is mentioned on this page:
https://developers.mattermost.com/integrate/webhooks/incoming/#parameters

For example with [Gatus custom alert](https://gatus.io/docs/alerting-custom) we override the channel but this laks the information of the 'Condition results' fields.
```yaml
      custom:
        url: "https://mattermost.localhost/hooks/hook_id"
        method: "POST"
        body: |
          {
            "channel":"my-channel","attachments": [{"title": "Gatus","title_link": "https://gatus-mattermost.localhost","color": "danger","text": "An alert for [ENDPOINT_GROUP]/[ENDPOINT_NAME] has changed status to [ALERT_TRIGGERED_OR_RESOLVED]\n[ENDPOINT_URL]"}]
          }
```

For this Feature the Gatus alert could be extended by an extra optional attribute `channel` which contains the channel name:
```yaml
      mattermost:
        webhook-url: my-webhook
        channel: my-channel
````

### Why do you personally want this feature to be implemented?

This feature makes it possible to use one webhook for all channels.
This keeps the configuration simple because we don't have to create and administrate a webhook for each channel.

### How long have you been using this project?

3 years
