### ISSUE TITLE
panic: invalid tls config: open fullchain.pem: no such file or directory

### ISSUE THREAD

**Issue by roughnecks** [TwiN/gatus#660]
### Describe the bug

Whenever I start the docker container I get the title's error, whatever I type in config.yaml, full or relative paths

### List the steps that must be taken to reproduce this issue

1. mkdir -p /home/user/docker/etc
2. cd /home/user/docker/etc
3. nano config.yaml

```
web:
  port: 23456
  tls:
    certificate-file: "fullchain.pem"
    private-key-file: "privkey.pem"
```

4. cp /etc/letsencrypt/live/domain/fullchain.pem .
5. cp /etc/letsencrypt/live/domain/privkey.pem .
6. sudo docker run -p 12345:12345 --mount type=bind,source="$(pwd)"/config.yaml,target=/config/config.yaml --name gatus twinproduction/gatus

### Version

latest docker
