### ISSUE TITLE
Add support for HTTP Basic Auth in endpoints

### ISSUE THREAD

**Issue by thomasvvugt** [TwiN/gatus#685]
### Describe the feature request

In HTTP endpoints, e.g. when checking "[STATUS] == 200", I would like to see the availability to pass on HTTP Basic credentials (username and password), similar to the security section.

Example endpoint configuration could be:
```
  - name: Authenticated endpoint
    url: "http://myservice:8080"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
    security:
      basic:
        username: admin
        password: YWRtaW4=  # base64 encoded
```

### Why do you personally want this feature to be implemented?

It would be perfect to monitor the HTTP status codes of some authenticated pages
