### ISSUE TITLE
Pushover send-on-resolved not working

### ISSUE THREAD

**Issue by toskium** [TwiN/gatus#688]
### Describe the bug

pushover send-on-resolved seemingly not working.

### What do you see?

I receive a pushover notification showing the endpoint being unhealthy

### What do you expect to see?

I do not receive a pushover notification when the endpoint is healthy again.

### List the steps that must be taken to reproduce this issue

Start the application.
Provoke an alarm.
Wait until success-threshold is exceeded.
No pushover alarm is sent.

### Version

5.7.0

### Additional information

the relevant parts of my config.yaml look like this:

```
alerting:
  pushover:
    application-token: mytoken
    user-key: myuserkey

endpoint-internal-defaults: &defaults_internal
  group: internal
  interval: 5m
  client:
    timeout: 10s
    insecure: true
  conditions:
    - "[STATUS] == 200"

endpoints:
  - name: Homepage Dashboard
    <<: *defaults_internal
    url: http://192.168.10.17:3000
    alerts:
      - type: pushover
        failure-threshold: 2
        success-threshold: 2
        send-on-resolved: true
        description: "Healthcheck Failed"
```
