### ISSUE TITLE
STARTTLS does not work work IMAP, workds with SMTP, though

### ISSUE THREAD

**Issue by meyergru** [TwiN/gatus#689]
### Describe the bug

When I connect an IMAP STARTTLS endpoint, I get an error. This works for an SMTP endpoint.

When I check both endpoints with openssl, they work fine. One has to say, that for "openssl s_client", you have to specify which protocol to use with -starttls, like smtp, imap a.s.o., but I see no way how to make this work in the Gatus documentation.

### What do you see?

```
Conditions:
X ~ [CONNECTED] (false) == true
X ~ [CERTIFICATE _EXPIRATION} (0) > 3d (0)

Errors:
- short response: * OK [CAPABILITY IMAPrev1 SASL-IR .... STARTTLS] Dovecot ready.

```

### What do you expect to see?

No error.

### List the steps that must be taken to reproduce this issue

I specify an endpoint using STARTTLS with SMTP like this:

```
endpoints:
  - name: SMTP Endpoint
    group: mail
    url: "starttls://smtp.localdomain:5870"
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      - "[CERTIFICATE_EXPIRATION] > 7d"

```

it works as expected. However, when I specify:

```
endpoints:
  - name: IMAP Endpoint
    group: mail
    url: "starttls://imap.localdomain:1430"
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      - "[CERTIFICATE_EXPIRATION] > 7d"

```

### Version

Gatus 5.7.0 (Dockerhub stable version)

### Additional information

The endpoints are provisioned with certificates issued by my own CA, which has been injected via a docker volume to /etc/ssl/certs/ca-certificates.crt. Both endpoints use the same multi-SAN certificate. The same error occurs when I add "client.insecure" to the definitions.
