### ISSUE TITLE
Allow alerting on external endpoints that do not receive a push within a configurable time frame

### ISSUE THREAD

**Issue by onedr0p** [TwiN/gatus#741]
that's great.
For step 3. , will it also include the negative "Said endpoint must automatically check if an alert has **_not_** been triggered" i.e. raise an alert if no result received within a specified period ? 
(aka push-based monitoring)

_Originally posted by @r3mi in https://github.com/TwiN/gatus/issues/722#issuecomment-2041015420_

**Comment by TwiN** [comment]
Thank you for creating the issue.

Now that external endpoints have been implemented (#722, #724), this should probably be the next feature related to external endpoints that gets implemented as they kind of go hand in hand, especially for those using external endpoints to test connectivity. If there's no connectivity, Gatus' API won't be reachable, which means that Gatus wouldn't be able to trigger an alert without this feature.

**The feature in question should allow the user to configure a duration under which an update is expected to be received.** 

Should the duration elapse with no new status update, a status should be created to indicate a failure to receive an update within the expected time frame. 

This should in turn cause https://github.com/TwiN/gatus/blob/28339684bfd9bb0e13bed4409f88e64bff31f3b2/watchdog/alerting.go#L13-L22 to be called, which would then lead to `handleAlertsToTrigger` being called (due to the new result indicating failure to receive an update having its `Success` field set to `false`), incrementing `NumberOfFailuresInARow` https://github.com/TwiN/gatus/blob/28339684bfd9bb0e13bed4409f88e64bff31f3b2/watchdog/alerting.go#L24-L27 & triggering whichever alerts should be triggered.


The only proper name I can think of for this feature is "dead man's switch", but as silly as it may sound, I don't like how that'd look on the configuration.

Just thinking out loud here
```yaml
external-endpoints:
  - name: ...
    dead-man-switch:
      duration-until-trigger-automatic-failure: 1h
    alerts: 
      - type: slack
        send-on-resolved: true
```

Another consideration to make is the interaction between this feature and maintenance. While the maintenance period should prevent alerts from being triggered, should failure status be pushed anyways? Perhaps this should be an additional parameter on the maintenance configuration (e.g. `maintenance.silence-dead-man-switch`)?

Anyways, just food for thoughts

**Comment by onedr0p** [comment]
> The only proper name I can think of for this feature is "dead man's switch", but as silly as it may sound, I don't like how that'd look on the configuration:

I've seen other services call this `heartbeat` instead of `dead man's switch`

**Comment by atch24** [comment]
I would love to see a feature similar to this feature request, just like implemented in healthchecks.io

This would allow to provide a cron schedule and then monitor crons and alert for crons that do not run or jobs that take too long to complete.

An example configuration might look like this:

```
external-endpoints:
  - name: ...
    heartbeat:
      schedule: 0 0 15 * *
      grace-period: 2m
```

**Comment by flohoss** [comment]
If you look at betterstack.com or Healthchecks.io, they both implement similar settings, although betterstack does not really go into much detail. They offer a separate maintenance setting per heartbeat, but this is already [covered](https://github.com/TwiN/gatus?tab=readme-ov-file#maintenance).

Seems like the settings that make most sense to me would be:

```yaml
external-endpoints:
  - name: ...
    heartbeat:
      # Define the scheduling method to use: "interval" or "cron".
      # "interval" runs based on a fixed duration between heartbeats.
      # "cron" runs at specific times defined by a cron expression.
      method: 'cron' # Choose either "cron" or "interval"

      # Use this field if the method is "interval".
      # Defines the duration between heartbeats. Valid units are:
      # "ns" (nanoseconds), "us"/"µs" (microseconds), "ms" (milliseconds),
      # "s" (seconds), "m" (minutes), "h" (hours).
      # -> https://pkg.go.dev/time#ParseDuration
      interval: '24h'

      # Use these fields if the method is "cron".
      # "cron" defines the schedule using a cron expression.
      # For example, "0 0 * * *" means midnight every day.
      cron: '0 0 * * *'

      # Specifies the timezone to use when evaluating the cron expression.
      # This is required only for "cron" and is ignored for "interval".
      timezone: 'Europe/Berlin'

      # Specifies the grace period to tolerate delayed heartbeats.
      # This applies to both "interval" and "cron".
      grace-period: '1h'
```

This would be awesome as i am currently running healthchecks and gatus but only need healthchecks for 2 pings from a backup every night. Not really feeling the need of running Django for this...

**Comment by pswilde** [comment]
I'd also really love this feature
I'm currently using Uptime Kuma, which does the job well, but I prefer Gatus' way of configuration

Uptime Kuma also uses the term "heartbeat" which fits well I think, which I have set for every 90000 seconds - a day plus an hour grace time), so previous comments talking about a grace-period would also be massively beneficial

![Image](https://github.com/user-attachments/assets/06f1d7e4-231c-4877-b233-b6706a0b4b81)

Thanks for the hard work on Gatus - great stuff!

**Comment by TwiN** [comment]
I think heartbeat makes sense. It's definitely on my radar, especially given how many :+1: this issue has amassed in the past year.

**Comment by a-waider** [comment]
Is there any progress on this topic?

**Comment by nvpreport** [comment]
Plus one for this feature 👍

**Comment by TwiN** [comment]
I started having a look at a possible implementation. 

Just thinking out loud here (rubber duck ~~debugging~~ programming): let's say we configure the heartbeat of an external endpoint with an interval of 1h, and no new result comes in for an hour, do we want to push a failed result/check? This would be the easiest way to implement this, as pushing a failed result would automatically trigger the alerts.

The sneaky thing with this implementation is that we could leverage the existing implementation for normal/internal endpoints here: https://github.com/TwiN/gatus/blob/00419a4b4a1322417d681ff606d88abc6bedb72e/watchdog/watchdog.go#L30-L34

As I think through this problem and go through the code, of course, past me is there to answer future me's questions: https://github.com/TwiN/gatus/blob/00419a4b4a1322417d681ff606d88abc6bedb72e/watchdog/watchdog.go#L55-L57

The statement above would no longer be true, as we'd now want to check external endpoints periodically -- but we'd do it using `external-endpoints[].heartbeat.interval` (if interval > 0)

**Comment by spencerhughes** [comment]
> let's say we configure the heartbeat of an external endpoint with an interval of 1h, and no new result comes in for an hour, do we want to push a failed result/check?

I think that this makes the most sense. The success/failure of a heartbeat check is, to me, saying "this is considered a success if we receive a ping before the heartbeat interval timer reaches zero, and if that timer reaches zero that is considered a failure." If your heart is supposed to beat once every second and it doesn't beat for >1 second, your heart has transitioned to a failure state.

As other commenters have mentioned as well, I think we would want to have a grace period configuration for heartbeat checks as well. This is helpful to prevent alert spam in the event that intermittent connectivity or system load delays the health check.

**Comment by TwiN** [comment]
> As other commenters have mentioned as well, I think we would want to have a grace period configuration for heartbeat checks as well. This is helpful to prevent alert spam in the event that intermittent connectivity or system load delays the health check.

@spencerhughes I'm thinking of just relying on the `failure-threshold` of the configured alert for now, as its main purpose _is_ to prevent alert spam.

This implementation will likely be pretty minimal. I expect people will want more features, such as different ways of configuring the interval as one of the previous comments mentioned (cron), or maybe even add a grace period configuration like you requested, but right now, I'm focusing on getting this feature out ASAP. 

When I implemented external endpoints, I knew there was _some_ interest in it, but given the number of votes a simple feature complementing external endpoints (this issue) received, it's become clear to me that a lot more people I anticipated are using external endpoints, hence why I'd rather focus on getting something out faster and perfecting it later.

**Comment by spencerhughes** [comment]
> I'm thinking of just relying on the failure-threshold of the configured alert for now

I think that makes sense. Re-using an existing parameter is cleaner/simpler than implementing something new that is effectively analogous, and it doesn't take a huge amount of brain power to do *fail if I don't get a heartbeat in 5 minutes* * *let this alert fail 3 times before alerting me* == *15 minute grace period* (though maybe I'm undermining my own point here because I can't 100% decide if that would be a 15 or 20 minute grace period :sweat_smile:).

**Comment by xXluki98Xx** [comment]
@TwiN Thanks for working on this feature!

I can already cover one of our use cases with it, but I'm particularly interested in the CRON support.

Our scenario: some pipelines run every weekday around 2 AM, and we want to monitor their successful execution — and be notified if they fail.
The challenge is daylight saving time, which can cause slight shifts. (GitLab.com runs on UTC, but our software runs locally on MEST/CEST.)

So if the Feature is ready, should I open a new Issue for the Cron Support?

**Comment by TwiN** [comment]
@xXluki98Xx The feature isn't ready, it's still a WIP I'm working on during my free time, but sure, once it's merged, you can absolutely create an issue suggesting cron support.

**Comment by TwiN** [comment]
So, I've got good news for the many interested. I just finished the first implementation for this - #1173 

The bad news is that before I merge this into master, I would really appreciate it if a few people could confirm that it works as intended on their end.

Docker command: `docker pull ghcr.io/twin/gatus:heartbeat` (created using https://github.com/TwiN/gatus/actions/runs/16601219374)

**Comment by markormesher** [comment]
I gave it a very quick test with a 1m timeout and it seems to be working! I'll set it up properly today for a real job and see how it goes.

**Comment by TwiN** [comment]
This is now available under `latest`. 
Let me know if there's any issues.

P.S. I'll be deleting `ghcr.io/twin/gatus:heartbeat` as it is no longer necessary

**Comment by darkrain-nl** [comment]
Quick test here works great. Thanks for the great work.

**Comment by TwiN** [comment]
Awesome, thank you folks. I'll be releasing this in v5.21.0 today or tomorrow.

**Comment by ghanjiboy** [comment]
Hi @TwiN , glad to see this feature implemented.  I have a question, I have about 20 monitors that fall in this category and they have different heartbeat intervals as they are jobs - some are hourly, some daily and some weekly.   I noticed that the monitor doesnt show up in the dashboard until at least one of the intervals has passed -this seems like a bug - but I wanted to check with you first.  

Here's an example:

```
external-endpoints:
  - name: BackupPostgres
    token: JvCWBHNScw
    heartbeat:
      interval: 180h
    group: job
  - name: BackupNFSServer
    token: EsyPeGcgtA
    heartbeat:
      interval: 25h
    group: job
```
