### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by shvkumara** [TwiN/gatus#745]
### Describe the bug

I am getting the "x509: certificate signed by unknown authority" error.
I am using the 
helm chart : `minicloudlabs/gatus`

versions:
    chart: `3.4.4`
    Appversion: `v5.10.0`

Below is my configMap data
```
data:
  config.yaml: |
    endpoints:
    - conditions:
      - '[STATUS] == 200'
      headers:
        X-APIKEY: <MyApiKey>
      insecure: true
      interval: 60s
      name: sample-api
      url: https://my-app-stg.av.cloud.pan.local/sample/v3/sample/healthcheck
```

I thought this was fixed in https://github.com/TwiN/gatus/issues/14

### Version

v5.10.0

**Comment by TwiN** [comment]
`insecure` is under `client`.

e.g.
```yaml
endpoints:
  - name: ...
    client:
      insecure: true
```

See https://github.com/TwiN/gatus?tab=readme-ov-file#client-configuration
