### ISSUE TITLE
Default alert settings not used for external endpoint

### ISSUE THREAD

**Issue by JELTAD** [TwiN/gatus#768]
### Describe the bug

I have setup discord alerts with some default-alert settings. When adding
```yml
alerts:
    - type: discord
```
to a normal endpoint, these default-alert settings are followed, but this is not the case with external endpoints. The other alert settings as title and webhook-url do work as expected.

**Comment by TwiN** [comment]
Can you provide a configuration with both a normal endpoint and an external endpoint to reproduce the issue? (you can modify the webhook, I just need something that can let me reproduce the issue locally)

**Comment by JELTAD** [comment]
Of course

```yml
alerting:
  discord:
    webhook-url: "https://discord.com/api/webhooks/"
    title: "Gatus"
    default-alert:
      enabled: true
      failure-threshold: 2
      success-threshold: 1
      send-on-resolved: true
      description: "Status changed"

endpoint-defaults: &endpoint-defaults
  interval: 60s
  conditions:
    - "[STATUS] == 200"
  alerts:
    - type: discord

endpoints:
  - name: Google
    url: https://www.google.com
    <<: *endpoint-defaults

external-endpoints:
  - name: ext-ep-test
    group: core
    token: potato
    alerts:
      - type: discord
```

The normal endpoint sends a message after 2 failures and when it succeeds again. The external one  sends a message after 3 failures and none when it succeeds again (the default behavior iirc) . The title for all alerts is correct.
