### ISSUE TITLE
Add support for DNS over TLS and DNS over HTTPS

### ISSUE THREAD

**Issue by onedr0p** [TwiN/gatus#784]
### Describe the feature request

It would be great if gatus could support DoH and DoT when using the DNS endpoint...

```yaml
endpoints:
  - name: example-dns-query
    url: "8.8.8.8" # Address of the DNS server to use
    url: "tcp-tls:1.1.1.1:853" # Address of the DNS server to use (DoT)
    # url: "https://1.0.0.2/dns-query" # Address of the DNS server to use (DoH)
    dns:
      query-name: "example.com"
      query-type: "A"
    conditions:
      - "[BODY] == 93.184.215.14"
      - "[DNS_RCODE] == NOERROR"
```

### Why do you personally want this feature to be implemented?

In some environments port 53 is nat'ed to an internal DNS server, using DoT or DoH can circumvent this.

### How long have you been using this project?

18 months+

**Comment by onedr0p** [comment]
It would also be great to support this in the checker field:

```yaml
connectivity:
  checker:
    target: tcp-tls:1.1.1.1:853
    interval: 1m
```

**Comment by laitco** [comment]
> ### Describe the feature request
> 
> It would be great if gatus could support DoH and DoT when using the DNS endpoint...
> 
> endpoints:
>   - name: example-dns-query
>     url: "8.8.8.8"                     # Address of the DNS server to use
>     # url: "tcp-tls:1.1.1.1:853"       # Address of the DNS server to use (DoT)
>     # url: "https://1.1.1.1/dns-query" # Address of the DNS server to use (DoH)
>     dns:
>       query-name: "example.com"
>       query-type: "A"
>     conditions:
>       - "[BODY] == 93.184.215.14"
>       - "[DNS_RCODE] == NOERROR"
> ### Why do you personally want this feature to be implemented?
> 
> In some environments port 53 is nat'ed to an internal DNS server, using DoT or DoH can circumvent this.
> 
> ### How long have you been using this project?
> 
> 18 months+
> 
> ### Additional information
> 
> _No response_

+1 for this feature

**Comment by onedr0p** [comment]
It does appear that DoT and DoH is supported by the library used here. https://github.com/miekg/dns

It doesn't look to hard to add, maybe I'll take a crack at it when I have free time.

**Comment by slashsbin** [comment]
It's actually already possible to do DoH tests, partially at least (without asserting the IP in response):
```yaml
endpoints:
  - name: cloudflare-doh
    url: "https://cloudflare-dns.com/dns-query?type=A&name=example.net"
    headers:
      accept: "application/dns-json"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].Status == 0"
      - "len([BODY].Answer) > 1"
```
Although the syntax is verbose IMHO, and a dedicated DoH support would be appreciated.
