### ISSUE TITLE
Included logo does not work

### ISSUE THREAD

**Issue by michael5941** [TwiN/gatus#818]
### Describe the bug

I want to set up my customized logo, but it can not work when Iconfig ui.logo in yaml.
I got error [api.ErrorHandler] Cannot GET /img/google.svg.
How can I fix this issue? Thank you!
This is my  configuration file
# docker-compose.yaml
```
version: '3.9'

  gatus:
    image: twinproduction/gatus:latest
    volumes:
      - ./config:/config
      - ./uidata/demo.svg:/uidata/demo.svg
    ports: 
      - 8080:8080
```
# config.yaml
```
ui:
  header: Example Company
  logo: "/uidata/google.svg"
  link: https://example.org
```

### What do you see?

Can not get customized logo when setting information in config.yaml.
![image](https://github.com/TwiN/gatus/assets/30205801/ceced357-822b-44e1-bce0-8e49d430977d)

### What do you expect to see?

Can get customized logo on the health check page.

### Version

v2.52.4
