### ISSUE TITLE
Endpoints: Send custom Token Header

### ISSUE THREAD

**Issue by onlynow2** [TwiN/gatus#846]
### Describe the bug

I'm trying to monitor my nextcloud instance with gatus.

There's an nextcloud app called "serverinfo", which can be accessed by the following url using curl in CLI and providing the "NC-Token" in the header:
`curl -H 'NC-Token: f65578a77feb8ba2ce584f15f50718fa2a4a94465748fb433a4f1b475a11acc8' -X GET https://your.nextcloud.com/ocs/v2.php/apps/serverinfo/api/v1/info`

The token is mandatory, otherwise an "not authorized" error will be thrown.

I've tired providing the header token within the `endpoints[].headers` field, without success.
I'm not quite sure if this is the right place for providing the token or if it's just a problem with the config.
The documentation was not quite clear to me in this point and I couldn't find an example elsewhere.

Is anyone able to point me in the right direction or post an example configuration snipped?

Thanks in advance.

### What do you see?

Header is not passed correctly, therefore "not authorized" error is thrown

### What do you expect to see?

Header is provided successfully, http response is available

### Version

5.11.0

**Comment by raojinlin** [comment]
Hi @onlynow2  could you please provide the Gatus configuration snippet you're using?

**Comment by onlynow2** [comment]
Sure, I've tried the following way:
```yaml
endpoints:
  - name: Nextcloud
    group: Testing
    interval: 5m
    client:
      timeout: 10s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
    url: "https://your.nextcloud.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json"
    headers:
      Content-Type: application/json
      Authorization: "NC-Token f65578a77feb8ba2ce584f15f50718fa2a4a94465748fb433a4f1b475a11acc8"
```

Yet, the conditions section might not work yet.
