### ISSUE TITLE
Feature Request: Add Yellow Color Option

### ISSUE THREAD

**Issue by raojinlin** [TwiN/gatus#865]
### Describe the feature request
At the moment, Gatus has two colors: red and green. Could you also add an option for a yellow color?

### A possible option
```yaml
  - name: tst-app
    group: not-important
    url: https://localhost:8080/healthz
    interval: 60s
    color: yellow
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*ok*)"
```
For custom checks, it could be something like:
```
curl -X POST -H "Authorization: Bearer 123456" "http://127.0.0.1:8080/api/v1/endpoints/core_ext-ep-test/external?success=warning&error=xxxx"
```
`success=warning` could show a yellow color in Gatus.

### Why do you personally want this feature to be implemented?
Some applications are not very critical.

### How long have you been using this project?
No response

### Additional information
No response
