### ISSUE TITLE
[ENDPOINT_URL] not resolving in alert message

### ISSUE THREAD

**Issue by mdraijer** [TwiN/gatus#924]
### Describe the bug

In an alert message we put the place holder [ENDPOINT_URL], but that is not resolved in the actual alerts.

### What do you see?

An alert without the URL of the endpoint being tested.

### What do you expect to see?

An alert with the URL of the endpoint being tested.

### Version

v5.10.0

**Comment by TwiN** [comment]
Please include the reproduction steps and an example configuration.

**Comment by mdraijer** [comment]
Apologies, forgot that vital information...

Consider this configuration:
```yaml
    alerting:
      mattermost:
        webhook-url: https://my-mattermost.com/hooks/xcgvhjhhjgcxgfbjknkjnbkj
        default-alert:
          enabled: true
          send-on-resolved: true
      custom:
        default-alert:
          enabled: true
          send-on-resolved: true
        placeholders:
          ALERT_TRIGGERED_OR_RESOLVED:
            TRIGGERED: "danger"
            RESOLVED: "good"
        url: "https://my-mattermost.com/hooks/vgcbdkjkcdblkjb"
        method: "POST"
        body: |
          {
            "channel":"my-alert-channel","attachments": [{"title": "My Gatus","title_link": "https://my-gatus.com","color": "[ALERT_TRIGGERED_OR_RESOLVED]","text": "**[ENDPOINT_GROUP]/[ENDPOINT_NAME]** has changed status to [ALERT_TRIGGERED_OR_RESOLVED]\n[ENDPOINT_URL]"}]
          }
    endpoints:
    - name: My Test Endpoint
      group: My Group
      url: "https://my-test-app.com"
      interval: 30s
      method: HEAD
      conditions:
      - "[STATUS] == 200"
      alerts:
      - type: mattermost
        description: "Went wrong on URL [ENDPOINT_URL]"
```

With the custom alerting type it is possible to add the actual monitored URL to the message. With the mattermost alerting type - which is much easier to configure, and therefore preferred - the monitored URL is not included in the message. It is fine that that is the default behaviour, but I want to be able to add the URL to the message. The only element I see where it can be added is the description, but here the place holder is not resolved.

**Comment by TwiN** [comment]
Ah, this is because alert placeholders are only supported for the custom alerting provider.

While it would be convenient to have it for all providers, it is ultimately not a necessity because in the alert, you know what the url is:
```yaml
    endpoints:
    - name: My Test Endpoint
      group: My Group
      url: "https://my-test-app.com"   <---- the url is here
      interval: 30s
      method: HEAD
      conditions:
      - "[STATUS] == 200"
      alerts:
      - type: mattermost
        description: "Went wrong on URL [ENDPOINT_URL]"  <---- so you can just copy it here too
```

Either way, these placeholders are just for the endpoint's body and its URL, not for the alert description.
