### ISSUE TITLE
tls: hanshake failure - client.insecure true doesn't work

### ISSUE THREAD

**Issue by PhilipWhiteside** [TwiN/gatus#932]
### Describe the bug

When using `client.insecure true` the check fails with the error `tls: hanshake failure`

### What do you see?

The check fails due to self signed certificate

### What do you expect to see?

The check to pass because it's marked as insecure

### List the steps that must be taken to reproduce this issue

```yaml
endpoints:
  - name: "05 Doorbell"
    url: "https://camera-05.lan/"
    client: 
      insecure: true
    group: "Cameras"
    interval: "5s"
    conditions:
      - "[STATUS] == 200"
```

### Version

v5.13.0

### Additional information

![Screenshot from 2024-12-13 23-35-10](https://github.com/user-attachments/assets/b67a540a-3727-45f2-a895-c69f176494f9)

It looks like it was patched in #547 that landed in https://github.com/TwiN/gatus/releases/tag/v5.6.0 . However, I'm on v5.13.0

**Comment by pnikonowicz** [comment]
I tested this on a new build with sha 83a555e3 using config:
```
  - name: insecure-tls
    group: core
    url: "https://expired.badssl.com"
    client:
      insecure: true
    interval: 5m
    conditions:
      - "[STATUS] == 200"
```
and was not able to reproduce the issue. it is my recommendation to close this issue. 

[created PR](https://github.com/TwiN/gatus/pull/942) to add additional testing in this area
