### ISSUE TITLE
[RESULT_ERRORS] parsed but empty

### ISSUE THREAD

**Issue by SeaweedbrainCY** [TwiN/gatus#951]
### Describe the bug

First of all, thanks for this project 

I am trying to configure a custom alert provider but fail to pass the result of the else check. 

My custom conf is the following one : 

```yml
custom:
        url:  http://*************/gatus/notify
        method : "POST"
        headers: {"X-Auth-Token": "****************"}
        body: |
          { "endpoint": "[ENDPOINT_NAME]",
            "conditions": "- [RESULT_ERRORS] -",
            "description": "[ALERT_DESCRIPTION]",
            "endpoint_url": "[ENDPOINT_URL]",
            "resolved": "[ALERT_TRIGGERED_OR_RESOLVED]"
          }
        default-alert:
          failure-threshold: 2
          success-threshold: 1
          send-on-resolved: true
```

### What do you see?

From my webhook end, here my what I receive : 
```json
{
    "endpoint": "example", 
    "conditions": "-  -", 
    "description": "example.com is down", 
    "endpoint_url": "[REDACTED]",  
    "resolved": "TRIGGERED"
}
```

### What do you expect to see?

I expect to receive the healthcheck result which works well for my endpoint as I recieve this health check on ntfy in parrallel : 
```
🔴 [STATUS] (502) == 200
🟢 [CERTIFICATE_EXPIRATION] > 7d
```

### List the steps that must be taken to reproduce this issue

1. Start the application
2. Configure a custom alert provider using the [RESULT_ERRORS] provider
3. Configure the following endpoint : 
```yaml
      - name: Test
        group: "Public services"
        interval: 10s
        url: https://example.com
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 7d"
        alerts:
          - type: custom
            description: "test is down"
          - type: ntfy
            description: "test is down"
```
4. Generate an downtime or resolve it

### Version

v5.15.0

### Additional information

I'll try to downgrade to previous version to try if it'll resolve the issue or not. I'll post the result once done below.
