### ISSUE TITLE
Encoding for body in custom alerting

### ISSUE THREAD

**Issue by egorsmkv** [TwiN/gatus#989]
### Describe the feature request

I have the following config:

```yaml
alerting:
  custom:
    url: "https://webhook.site/80437f67-6027-4d3d-acf8-fd2c26f9e5f6"
    headers:
      "Content-Type": "application/json"
    method: "POST"
    body: |
      {
        "message": "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_GROUP] - [ENDPOINT_NAME] - [ALERT_DESCRIPTION] - [RESULT_ERRORS]"
      }
```

When a trigger executed Gatus send a request:

<img width="1364" alt="Image" src="https://github.com/user-attachments/assets/d2a9d71a-2ed8-45b8-ae59-2d0b451c77da" />

As you can mention, we have two `"` here:

<img width="1370" alt="Image" src="https://github.com/user-attachments/assets/7babe7e0-26dd-4c1e-b8ef-b080f06281c7" />

It leads to an error on the webhook part (it can't decode the body) so my feature request is to add possibility for it.
